### PR TITLE
docs: Fix markdownlint problems by using different headers instead of different links

### PR DESCRIPTION
**Pull request by rfay**
This reverts commit 41f38c70098d6ba3613cc890e0334c88d2f4ad6a.

See discussion in #6197 

I had to do a --no-verify to push this because I have pre-push checks enabled

### CODE REVIEW

**Comment by stasadev** [comment]
I don't see a way how to fix it quickly.

Perhaps we can simply not use such anchors, but change them:

```diff
-## Maintaining `ddev-dbserver` MySQL 5.7 & 8.0 ARM64 Images
+## Maintaining `ddev-dbserver` MySQL 5.7 and 8.0 ARM64 Images
```

```diff
-## Fork / Clone the DDEV Repository
+## Fork or Clone the DDEV Repository
```

**Comment by rfay** [comment]
That's a good solution.

**Comment by rfay** [comment]
OK, see what you think of this @stasadev

**Review by stasadev — APPROVED** [review]
It looks great, thank you!

I like that it is settled now.

**Pull request merged**
