### PR TITLE
docs: improve and simplify codespaces guide, use separate script

### PR DESCRIPTION
**Pull request by mandrasch**
## The Issue

- described in https://github.com/ddev/ddev/issues/5288

## How This PR Solves The Issue

- remove "configure devcontainer" section, since it only adds this bare minimum template:

image

- remove `ddev config --omit-containers=ddev-router` (https://github.com/ddev/ddev/issues/5288#issuecomment-1687151750)

- use separate bash script for `postCreateCommand` since users may want to add more commands

## Manual Testing Instructions

- [x] test guide with non-codespaces repository - thanks very much @tyler36 
- [x] ran docs generation locally

Here is a demo repo for following the guide:
https://github.com/mandrasch/ddev-codespaces-demo

## Automated Testing Overview

- no

## Related Issue Link(s)

- https://github.com/ddev/ddev/issues/5288
- https://github.com/ddev/ddev.com-front-end/pull/86

## Release/Deployment Notes

no

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5290"></a>

### CODE REVIEW

**Comment by tyler36** [comment]
Thanks for this.

- HTTP (forwarded `8080`) opens HTTPS version of site.
- Xdebug works when you install the extension, add the launch snippet. It automatically forwards the port which is nice.
- Mailhog page opens and correctly captured/displayed mail
- `400` error when trying to access the forwarded HTTPS version (port `8443`)
- `404` error when use the `ddev launch` command.

**Comment by rfay** [comment]
> 400 error when trying to access the forwarded HTTPS version (port 8443)

I'm not sure which https port you're talking about here @tyler36 , but in general, the Codespaces router can't trust DDEV's https because there's no way to inject a CA into it. As a result, it can't decode information coming from any DDEV-based https port.

**Comment by mandrasch** [comment]
Great, thanks very much for clarification @rfay! (I assumed this a while ago, but was never sure)

(Background:

There is automatically a port created when `ddev start` is called within codespaces:

image

image

We could also label the http port and https port differently to avoid confusion, but don't know what good label titles would be?

```
    "8080": {
      "label": "web http"
    },
    "8443": {
      "label": "web https"
    },
 ```)
 
 In general this PR is good to go from my perspective, thanks so much @tyler36 for testing it with a fresh set of eyes 🙂

**Comment by mandrasch** [comment]
In general this PR is good to go from my perspective, thanks so much @tyler36 for testing it with a fresh pair of eyes 🙂 👍

**Comment by mandrasch** [comment]
Mh ... quick update: In my tests the ddev site could also be opened via port `8443` 🤔 
https://github.com/mandrasch/ddev-codespaces-demo

**Comment by rfay** [comment]
Yes, I guess you're right; they must be ignoring cert failure I guess? Even curl doesn't work here:

```
$ curl -I https://localhost:8443
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

However, I can `curl -I -k https://localhost:8443`:
```
$ curl -I -k https://localhost:8443
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 22 Aug 2023 22:21:29 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
```

I can't even get curl to work with `mkcert -install` being done and all.  Perhaps they don't let you install a system CA, etc.

**Comment by rfay** [comment]
I actually think we're doing too much here. IMO it should just be: 

```json
{
  "image": "mcr.microsoft.com/devcontainers/universal:2",
  "features": {
        "ghcr.io/ddev/ddev/install-ddev:latest": {}
  }
}
```

And perhaps we should tell them about `ddev config` and such. Advanced users can go farther and do fancy things. But my experience with this is just fine.

**Comment by rfay** [comment]
However, studying this I discovered:
* https://github.com/ddev/ddev/issues/5292
* https://github.com/ddev/ddev/issues/5291

**Comment by mandrasch** [comment]
> I actually think we're doing too much here. IMO it should just be: ... And perhaps we should tell them about ddev config and such. Advanced users can go farther and do fancy things. But my experience with this is just fine.

Very happy to follow your lead! No hard feelings if this PR get's closed for now. 😉 

Just my assumption:
- devs most likely also want the extra bash script, because the current one liner gets way to big: `"postCreateCommand": "chmod +x .devcontainer/setup_project.sh && .devcontainer/setup_project.sh"` 
- for me it was a pain to set it up, because you need time-consuming (full) rebuilds to test it
- when we remove `postCreateCommand` a lot of the awesomeness of codespaces + ddev is gone imho 

So my suggestion would be to at least link to an "official" reference where the separate bash script is explained which setups an existing ddev project in the repository automatically? Maybe in the "Extending" docs section? 🤔 

Regarding this PR: Should I change something here?

> However, studying this I discovered:
> 
> * [`ddev start` downloads traefik image when router is excluded #5292](https://github.com/ddev/ddev/issues/5292)
> * [`ddev describe` shows `router: traefik` when no router.  #5291](https://github.com/ddev/ddev/issues/5291)

Oh. Can this be fixed within ddev or should I re-add `ddev config global --omit-containers=ddev-router`?  (if we follow through with this PR)

**Comment by rfay** [comment]
None of this is about the traefik router's use... that part is working fine. I just noticed that it's pre-downloading the traefik docker image (which doesn't get used), so it shouldn't be doing that.

**Comment by rfay** [comment]
As far as how much we should tell people to do, I'm in favor of just telling them to add the one line (about the ddev feature) and then giving them a link showing how they can do other things, like running a script.

**Comment by mandrasch** [comment]
Just fiy:

Since today I noticed this error with this [setup](https://github.com/mandrasch/ddev-codespaces-demo/blob/main/.devcontainer/setup_project.sh): 

```
2023-08-24 05:35:45.006Z: Status: Downloaded newer image for traefik:v2.10
2023-08-24 05:35:45.026Z: docker.io/library/traefik:v2.10
2023-08-24 05:36:00.913Z:  Network ddev-hello-world_default  Created 2023-08-24 05:36:00.914Z: 
2023-08-24 05:36:01.159Z:  Container ddev-hello-world-web  Created 
2023-08-24 05:36:01.188Z:  Container ddev-hello-world-db  Created 
2023-08-24 05:36:02.375Z:  Container ddev-hello-world-db  Started 
2023-08-24 05:36:02.604Z:  Container ddev-hello-world-web  Started 2023-08-24 05:36:02.606Z: 
2023-08-24 05:36:03.780Z: Failed waiting for web/db containers to become ready: web container failed: log=, err=container /ddev-hello-world-web unhealthy:  2023-08-24 05:36:03.785Z: 
2023-08-24 05:36:03.791Z: Something is wrong with docker or colima and /mnt/ddev_config is not mounted from the project .ddev folder. This can cause all kinds of problems. 
2023-08-24 05:36:04.295Z: Failed to start hello-world: container(s) failed to become healthy before their configured timeout or in 120 seconds. This may be just a problem with the healthcheck and not a functional problem. (container 'web' exited, please use 'ddev logs -s web' to find out why it failed) 2023-08-24 05:36:04.297Z: 
2023-08-24 05:36:04.319Z: postCreateCommand failed with exit code 1. Skipping any further user-provided commands.

2023-08-24 05:36:04.347Z: Error: Command failed: /bin/sh -c chmod +x .devcontainer/setup_project.sh && .devcontainer/setup_project.sh
```

`ddev start` manually works fine after this. Could be related to latest additions to `docker-in-docker` (integrated in universal image), https://github.com/devcontainers/features/issues/660. 

I asked the maintainers here how to get the image and docker-in-docker-version for debug info: https://github.com/devcontainers/features/issues/634#issuecomment-1682620353

**Comment by mandrasch** [comment]
Hey @rfay, thanks very much for feedback! 

My updated quick proposal for simplifying it:

https://ddev--5290.org.readthedocs.build/en/5290/users/install/ddev-installation/

I updated the one liner from

`"postCreateCommand": "bash -c 'ddev debug download-images && ddev poweroff'"`

to

`"postCreateCommand": "bash -c 'ddev debug download-images && ddev poweroff'"`

But after seeing the preview: It would also be an option to completely move the `postCreateCommand` one liner to the advanced section as well, like you already proposed. Guess it does not add very much benefit for first-time users who just want to checkout ddev in a cloud environment.

**Comment by rfay** [comment]
> Something is wrong with docker or colima and /mnt/ddev_config is not mounted

This basically means that there is a significant problem; this normally only happens on Colima, which is why the code is there. I guess the [ddev start -y](https://github.com/mandrasch/ddev-codespaces-demo/blob/c033552ac94e17c812781a77b49267177751d015/.devcontainer/setup_project.sh#L14) is what failed here. Is it possibly the whole same problem with docker not running yet? Do we need to do a docker wait loop here as well? 

> "postCreateCommand": "bash -c 'ddev debug download-images && ddev poweroff'"

I'm not at all sure that the `ddev debug download-images` is offering value in this context either. I know the `ddev poweroff` is important for restarting Codespaces instances. 

> My updated quick proposal for simplifying it: https://ddev--5290.org.readthedocs.build/en/5290/users/install/ddev-installation/

I like the way you're clearing the way for a quick start and leaving the complicated stuff for later. This will work for me. Consider removing the postCreateCommand if we don't absolutely need `ddev poweroff` in the normal case. 

Overall, this is very welcome and your maintenance of it is so much appreciated. When you say it's ready I'll pull it.

**Comment by rfay** [comment]
Looks like https://github.com/devcontainers/features/issues/634#issuecomment-1692306977 relates to the problem you saw, so maybe docker isn't really up before it lets things go forward. So strange that they're struggling with these things:

> Important Note: /usr/local/share/docker-init.sh which starts/retries dockerd is added to the entrypoint command. This command runs in the background and is not a blocking script for the container startup. Since it's in the background, onCreateCommand/postCreateCommand/postStartCommand could all start executing before docker is fully running. If it takes docker too long, that could introduce flakiness in those lifecycle scripts.

**Comment by mandrasch** [comment]
Thanks very much @rfay for information and appreciation, very happy to help here (and hope that there are robust ways of using this technology in future, kind of a wild ride in the past weeks 😄 ).

I moved the `postCreateCommand` to advanced usage because of the issues.

Test repository for only using the most simple config, if anyone wants to test it in Codespaces:
https://github.com/mandrasch/ddev-codespaces-demo/tree/ddev-codespaces-simple

```
{
  "image": "mcr.microsoft.com/devcontainers/universal:2",
  "features": {
    "ghcr.io/ddev/ddev/install-ddev:latest": {}
  },
}
```

I'll let you know when this is PR finished for review, should be in the next days.

**Comment by mandrasch** [comment]
Hi @rfay, I added some additional information below the simplified starting guide which I found to be important for working with Codespaces. 

Ready for review,

Happy to implement any change / removal / edit requests!  🙂  Cheers!

**Comment by rfay** [comment]
Ooops, just a bit more work to do in the spellcheck. If `DDEVs` was meant to be `DDEV's` (possessive) then change that too.

**Comment by mandrasch** [comment]
(Oh, was not aware of the automatic spell check. Nice workflow! :+1:)

Fixed.

**Pull request merged**
