### PR TITLE
Rename markdownlint settings to avoid duplicate settings in VSC [skip ci]

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Issue

At the moment the rules used by the markdownlint extension for VSC are defined in the workspace settings. All settings defined in the `.markdownlintrc` have to be copied to the workspace settings therefor.

## How This PR Solves The Issue

To avoid duplicate markdownlint settings for VSC the existing config is renamed to `.markdownlint.jsonc` and the related workflow is changed properly to use this file now.

### CODE REVIEW

**Comment by gilbertsoft** [comment]
Another possibility would be just rename the existing config and adapt the docscheck workflow. Maybe would be the better solution...

**Review by rfay — COMMENTED** [review]
Wow, what is `jsonc` ?

**Comment by gilbertsoft** [comment]
> Wow, what is `jsonc` ?

`.jsonc` is JSON with comments.

**Comment by rfay** [comment]
Yay for jsonc!

**Review by rfay — APPROVED** [review]
Looks good to me, let me know when you want me to pull it. Will vscode now automatically look at the .markdownlintrc.jsonc or did that get removed accidentally? I saw it before...

**Comment by gilbertsoft** [comment]
> Looks good to me, let me know when you want me to pull it. Will vscode now automatically look at the .markdownlintrc.jsonc or did that get removed accidentally? I saw it before...

Yes, the extension of David will lookup this file automatically (also some others). I also assume other extensions for other editors or the editors will do the same.

You can pull it at anytime, it's ready and no other changes planed for the moment.

**Pull request merged**
