### PR TITLE
fix: avoid instrumentation of project if none is loaded, fixes #5065

### LINKED ISSUE #5065: Panic when `instrumentation-opt-in` enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

_No response_

### Expected Behavior

Don't throw an error.

### Actual Behavior

```bash
$ ddev version
 ITEM             VALUE                                         
 DDEV version     v1.22.0-alpha3-29-g9b3b0d9b                   
 architecture     amd64                                         
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0-beta1 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0-beta1             
 docker           24.0.2                                        
 docker-compose   v2.18.1                                       
 docker-platform  dev                                           
 mutagen          0.17.1                                        
 os               linux                                         
 router           traefik:v2.10                                 
 web              ddev/ddev-webserver:v1.22.0-beta1             
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d8 pc=0x91d79b]

goroutine 1 [running]:
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).GetOmittedContainers(...)
        /home/runner/work/ddev/ddev/pkg/ddevapp/ddevapp.go:371
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).TrackProject(0x0)
        /home/runner/work/ddev/ddev/pkg/ddevapp/amplitude_project.go:36 +0x7b
github.com/ddev/ddev/cmd/ddev/cmd.glob..func48(0x10e72c0, {0x112cda0?, 0x0?, 0x0?})
        /home/runner/work/ddev/ddev/cmd/ddev/cmd/root.go:98 +0x86
github.com/spf13/cobra.(*Command).execute(0x10e72c0, {0x112cda0, 0x0, 0x0})
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:876 +0x770
github.com/spf13/cobra.(*Command).ExecuteC(0x10ea4c0)
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:902
github.com/ddev/ddev/cmd/ddev/cmd.Execute()
        /home/runner/work/ddev/ddev/cmd/ddev/cmd/root.go:152 +0x25
main.main()
        /home/runner/work/ddev/ddev/cmd/ddev/main.go:28 +0xc5
```

### Steps To Reproduce

1. Use the latest `ddev` binary.
2. `ddev config global --instrumentation-opt-in=true`
3. Run `ddev version` or `ddev config global`.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Issue

- #5065

## How This PR Solves The Issue

Avoids instrumentation of the project if none is available.

## Manual Testing Instructions

Run `ddev --version` in a folder without DDEV config.

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5066"></a>

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
Shouldn't we also fix the place where it uses the invalid data? pkg/ddevapp/ddevapp.go:371

https://github.com/ddev/ddev/blob/9b3b0d9b241bbd32059a85ad57deb6312323796f/pkg/ddevapp/ddevapp.go#L371

Seems like that also should have been initialized? Or is it the `app` itself that doesn't exist here?

**Comment by gilbertsoft** [comment]
> Shouldn't we also fix the place where it uses the invalid data? pkg/ddevapp/ddevapp.go:371
> 
> https://github.com/ddev/ddev/blob/9b3b0d9b241bbd32059a85ad57deb6312323796f/pkg/ddevapp/ddevapp.go#L371
> 
> Seems like that also should have been initialized? Or is it the `app` itself that doesn't exist here?

Yes, app does not exist, that's the problem here.

**Comment by stasadev** [comment]
```text
$ ddev version
 ITEM             VALUE                                         
 DDEV version     v1.22.0-alpha3-30-gb57c5900                   
 architecture     amd64                                         
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0-beta1 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0-beta1             
 docker           24.0.2                                        
 docker-compose   v2.18.1                                       
 docker-platform  dev                                           
 mutagen          0.17.1                                        
 os               linux                                         
 router           traefik:v2.10                                 
 web              ddev/ddev-webserver:v1.22.0-beta1             
 
Instrumentation is opted in, but AmplitudeAPIKey is not available. This usually means you have a locally-built ddev binary or one from a PR build. It's not an error. Please report it if you're using an official release build.
```

Looks like it is impossible to test this build from PR.

I tried my local build instead. I placed some dummy values ​​in `pkg/versionconstants/versionconstants.go` and configured the `Makefile`.

I use OpenSnitch to inspect my internet traffic and I see `api2.amplitude.com` in my connections, and DDEV works if I disable the internet.

No more errors :+1:

**Review by rfay — APPROVED** [review]
Thanks for getting to the bottom of this!

**Pull request merged**
