### PR TITLE
fix: provide example .ddev/php folder and README, fixes #6052

### LINKED ISSUE #6052: Project .ddev/php directory should be created with example and README.txt
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

Most of our directories have examples and README.

* Do the same for .ddev/php
* Add to gitignore

### Actual Behavior

c

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #6052 

## How This PR Solves The Issue

Add .php directory with example and readme

## Manual Testing Instructions

* `ddev start`
* Review the provided files in .ddev/php
* Verify that nothing is added to the git index (`git status`) should not show anything.

### CODE REVIEW

**Comment by tyler36** [comment]
#6052 said to add a `gitignore`. However, this PR doesn't include one. 

Is this intentional?

**Comment by tyler36** [comment]
Confirmed.

## Test

### Latest

1. Check DDEV version

```shell
$ ddev -v
ddev version v1.23.0-beta1
```

1. Create a new project

```shell
mkdir 6052
cd 6052
```

1. Configure DDEV, accepting all defaults.

```shell
ddev config
```

1. Start DDEV 

```shell
ddev start
```

1. Confirm `.ddev/php` does NOT exist.

```shell
$ ls .ddev/php -a
ls: cannot access '.ddev/php': No such file or directory
```

### PR

1. Install PR's DDEV
1. Check version

```shell
$ ddev -v   
ddev version v1.23.0-beta1-10-g34a50e131
```

1. Start DDEV 

```shell
ddev start
```

1. Confirm `.ddev/php` exists
  
```shell
$ ls .ddev/php -a
.  ..  README.txt  php-example.ini.example
```

**Comment by rfay** [comment]
Because the two files are `readme.txt` and `*.example` they're already ignored, so I didn't have to add an explicit case, but thanks for paying attention!

**Review by stasadev — APPROVED** [review]
Tested `git status`, everything works as expected 👍

**Pull request merged**
