### PR TITLE
[docs] Rescue intentional line breaks

### PR DESCRIPTION
**Pull request by mattstein**
## The Issue

`.editorconfig` improvements in #4712 strip trailing spaces, which in Markdown removes two-space line endings (`  `) than translate into `<br>` elements.

## How This PR Solves The Issue

This removes the problematic `trim_trailing_whitespace = true` setting, re-adds two-space line endings that have since been stripped out of Markdown files, and fixes some other mangled spacing I noticed along the way.

The result allows Markdown to continue operating like someone would expect, without needing to resort to using `<br>` elements all over the place or unwittingly having their `  ` breaks stripped on save.

> **Note** 
> After further discussion, this PR changed from originally inserting `<br>` elements to reverting `trim_trailing_whitespace = true`.

## Manual Testing Instructions

[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect [the automatic build](https://ddev--4763.org.readthedocs.build/en/4763/).

## Automated Testing Overview

n/a

## Related Issue Link(s)

- #4745 
- #4712

## Release/Deployment Notes

n/a

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4763"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Sorry if I'm being dense, but if trim_trailing_whitespace makes us dance around with `<br>` everywhere, and you have to know magic knowledge to accomplish that, then let's remove the trim_trailing_whitespace instead. 

Normal markdown treats double linefeeds with respect. We'd rather have "normal" markdown. 

Am I lost still?

**Comment by mattstein** [comment]
I brought this up [here](https://github.com/ddev/ddev/pull/4739#issuecomment-1464662209), reiterated again why `trim_trailing_whitespace` is useful [here](https://github.com/ddev/ddev/pull/4745#issuecomment-1465268499), and you suggested a PR to fix the Markdown and keep `trim_trailing_whitespace` [here](https://github.com/ddev/ddev/pull/4745#issuecomment-1466339250).

This is that PR.

The `trim_trailing_whitespace` setting [is still enabled](https://github.com/ddev/ddev/blob/master/.editorconfig#L15) and those line breaks are stripped out. I don’t care what happens with the setting, I’m just trying to save the line breaks I added on purpose and I don’t want to keep circling the issue of what we do with that setting.

If you want me to drop `trim_trailing_whitespace` and turn those `<br>`’s back into double spaces again I can do that instead.

**Comment by rfay** [comment]
I'm the one that thinks trailing whitespaces do no harm. I apologize about this confusion, but I never thought this was a problem that needed solving. I guess we all think we're not being listened to. Do you think the trailing spaces is even a problem that needs solving? Does anybody but @gilbertsoft think it's a problem that needs solving?

**Comment by mattstein** [comment]
> Do you think the trailing spaces is even a problem that needs solving?

Not in Markdown, no. But I can’t speak for the whole codebase or @gilbertsoft’s intentions—just defending my precious line breaks.

**Comment by mattstein** [comment]
@rfay Updated my approach here along with the description. Ready to review again.

**Review by rfay — APPROVED** [review]
Can we feel the pain receding?

**Pull request merged**
