### PR TITLE
build: bump traefik to 2.11

### PR DESCRIPTION
**Pull request by nilsandresen**
## The Issue

Traefik got updated to version 2.11.

## Summary by CodeRabbit

- **New Features**
	- Updated Traefik to version 2.11 for improved routing capabilities.
	- Added monitoring capabilities with the `TRAEFIK_MONITOR_PORT` set to `10999`.
	- Enhanced container with utility tools (`bash`, `curl`, `htop`, `vim`) for better troubleshooting and debugging experience.

### CODE REVIEW

**Comment by rfay** [comment]
Thanks for tracking this @nilsandresen ! We can sure try this out. It does require pushing an image. I'll see if I can do that. 

I'm interested to know why you're paying such good attention. Is there something you're looking for in 2.11? (I saw the release go by, but didn't read carefully and actually thought we were tracking 2.x)

**Comment by rfay** [comment]
Rebased, updated reference, pushed the image, tests are running, thanks.

**Comment by nilsandresen** [comment]
@rfay We are using traefik as a router for some docker containers and I ran updates there today. Then I remembered the ddev router runs on traefik aswell and I thought why not open a PR.

**Comment by rfay** [comment]
Thanks @nilsandresen - Do you do any custom config of traefik in DDEV? I always love to hear how people are using this feature.

**Comment by rfay** [comment]
I also see that 3.0.0 is at rc1 status, and wonder what that will mean to us. We may want to get 3.0.0 in before DDEV v1.23.0, which is coming in the next couple of months.

**Comment by nilsandresen** [comment]
> Thanks @nilsandresen - Do you do any custom config of traefik in DDEV? I always love to hear how people are using this feature.

In DDEV not, I use traefik outside of DDEV aswell. I'm using it as reverse proxy with automatic SSL Certs.

**Comment by rfay** [comment]
> In DDEV not, I use traefik outside of DDEV aswell. I'm using it as reverse proxy with automatic SSL Certs

One of the key things that hasn't been studied in DDEV with traefik is using Let's Encrypt, so the old nginx-proxy router recipe is still what I and other people are using. Would love to have you take a look at this if you're interested, https://ddev.readthedocs.io/en/latest/users/topics/hosting/

**Comment by nilsandresen** [comment]
> > In DDEV not, I use traefik outside of DDEV aswell. I'm using it as reverse proxy with automatic SSL Certs
> 
> One of the key things that hasn't been studied in DDEV with traefik is using Let's Encrypt, so the old nginx-proxy router recipe is still what I and other people are using. Would love to have you take a look at this if you're interested, https://ddev.readthedocs.io/en/latest/users/topics/hosting/

Yeah I might take a look. If I found out something interesting should I share it on discord, or a discussion?

**Comment by rfay** [comment]
Just open a PR! Thanks! Happy to discuss it anywhere though.

**Review by rfay — APPROVED** [review]
Looks good, tests are good, thanks!

**Pull request merged**
