### PR TITLE
build: Bump drush 8 version to 8.5.0

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

Drush 8 (used for Drupal 7 and probably backdrop) got a new release for the first time in a long time, to 8.5.0

This bumps to 8.5.0.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
You might want to use caution before deploying, I have received reports of the phar returning errors during update operations.

```
$ ./drush up drupal
Update information last refreshed: Wed, 11/27/2024 - 16:06
 Name    Installed Version  Proposed version  Message                   
 Drupal  7.72               7.102             SECURITY UPDATE available 


Code updates will be made to drupal core.
WARNING:  Updating core will discard any modifications made to Drupal core files, most noteworthy among these are .htaccess and robots.txt.  If you have made any modifications to these files, please back them up before updating so that you can re-create your modifications in the updated version of the file.
Note: Updating core can potentially break your site. It is NOT recommended to update production sites without prior testing.

Do you really want to continue? (y/n): y
TYPO3\PharStreamWrapper\Exception: Unexpected file extension in "phar:///var/www/html/drush/commands/pm/version_control" in      [error]
/var/www/html/misc/typo3/drupal-security/PharExtensionInterceptor.php:38
Stack trace:
#0 /var/www/html/misc/typo3/phar-stream-wrapper/src/Behavior.php(72):
Drupal\Core\Security\PharExtensionInterceptor->assert('phar:///var/www...', 'url_stat')
#1 /var/www/html/misc/typo3/phar-stream-wrapper/src/Manager.php(115):
TYPO3\PharStreamWrapper\Behavior->assert('phar:///var/www...', 'url_stat')
```

Haven't looked into it myself yet.

**Comment by heddn** [comment]
I've already communicated with @greg-1-anderson  and opened https://github.com/drush-ops/drush/issues/6172

**Comment by greg-1-anderson** [comment]
@rfay What do you think about changing the installation method of Drush on ddev to use `git clone` and `composer install` instead of downloading the .phar? Along the same lines as [my previous comment about old php versions](https://github.com/drush-ops/drush/issues/4979#issuecomment-1470892504), I am thinking about removing support for the Drush 8 phar entirely, not just for old php versions. The box phar builder sometimes causes unpredictable results. I'm going to investigate a bit more before deciding.

**Comment by rfay** [comment]
@greg-1-anderson We'll do it any way you prefer. If we just want a `drush8` in /usr/local/bin... What's the way to get that? This?
```
mkdir -p /usr/local/src/drush
git clone -b 8.x https://github.com/drush-ops/drush /usr/local/src/drush8
cd /usr/local/src/drush8
ln -s /usr/local/src/drush8/drush /usr/local/bin/drush8
```

**Comment by rfay** [comment]
@greg-1-anderson see what you think about https://github.com/ddev/ddev/pull/6780/files#diff-ddc28b17c63eedfc281d63de8ae258a7b18a40b47b68b275df4c460a630cdcf2R131-R139

I'll wait for your next release before pulling this.

**Comment by rfay** [comment]
@greg-1-anderson says this is OK for our v1.24.0 release.

**Comment by stasadev** [comment]
Rebased and building new images.

**Pull request merged**
