### PR TITLE
feat: more readable formatting of lists of files, fixes #5985

### LINKED ISSUE #5985: "Using nginx snippets" notification could have improved formatting
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

NA

### Expected Behavior

`ddev` could report `nginx` snippets in a more readable fashion (?):

```
Using nginx snippets: [
  /Users/diego/some-project/.ddev/nginx/some.conf,
  /Users/diego/some-project/.ddev/nginx/some-other.conf
]
Custom configuration, including snippets, is only updated on project restart.
Run `ddev restart` if you do not see your configuration in effect.
```

Of course, the above could be smarter about other snippets or servers. I'm not familiar with other setups.

### Actual Behavior

`ddev` reports `nginx` snippets like:

```
Using nginx snippets: [/Users/diego/some-project/.ddev/nginx/some.conf /Users/diego/some-project/.ddev/nginx/some-other.conf]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
```

### Steps To Reproduce

1. Use a snippet in `.ddev/nginx`
2. Restart the project
3. Message is printed in hard to read format

### Anything else?

See: https://github.com/ddev/ddev/blob/master/pkg/ddevapp/config.go#L613

### PR DESCRIPTION
**Pull request by penyaskito**
## The Issue

E.g. nginx snippets are printed as 

```
Using nginx snippets: [/Users/diego/some-project/.ddev/nginx/some.conf /Users/diego/some-project/.ddev/nginx/some-other.conf]
```

which some users said wasn't very readable.

This provides a new formatting of 
```
Using nginx snippets: [
  /Users/diego/some-project/.ddev/nginx/some.conf,
  /Users/diego/some-project/.ddev/nginx/some-other.conf
]
```

## How This PR Solves The Issue

Added new util function `func FilesToReadableOutput(slice []string) (response string, err error)` and uses that when warning about nginx snippets, mysql conf, php conf and entrypoint scripts.

## Manual Testing Instructions

Create a new project or use an existing one.

Create a couple of snippets:

```
mkdir -p .ddev/nginx/
touch .ddev/nginx/redirect.conf
touch .ddev/nginx/another-redirect.conf
```

Run `ddev start` and you should see those files listed.

## Automated Testing Overview

Added test. Run with `go test -v -run TestFilesToReadableOutput ./pkg/util/`

### CODE REVIEW

**Review by stasadev — CHANGES_REQUESTED** [review]
This is a really good output!

I want to reuse it for something else, like the suggestion commands in #5978 to convert this:

`}, please use 'ddev logs -s web' and 'docker logs ddev-d10-web' and 'docker inspect --format "{{ json .State.Health }}" ddev-d10-web' to find out why it failed`

to:

```
}, please use the command(s) to find out why it failed [
    ddev logs -s web
    docker logs ddev-d10-web
    docker inspect --format "{{ json .State.Health }}" ddev-d10-web
]
```

@penyaskito, could you please remove the commas and rename `FilesToReadableOutput` to something more generic like `ArrayToReadableOutput`?

**Comment by penyaskito** [comment]
@stasadev Done the requested changes. 

I also looked at how to use it for commands suggestions and looks like the easiest would be doing it directly on `getSuggestedCommandForContainerLog`. Is that what you expected? Should it happen on this PR or would you like a separate one?

**Review by stasadev — APPROVED** [review]
Thank you!

**Comment by stasadev** [comment]
> Should it happen on this PR or would you like a separate one?

I'll make a new one, as it will require more wording changes in the places where `getSuggestedCommandForContainerLog` will be used.

**Pull request merged**
