### PR TITLE
build: bump upload-artifact to v4 and fix mkcert.exe in tarball/zipball [skip ci]

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* upload-artifact is deprecated and needs to bump to v4
* mkcert.exe in tarball/zipball is wrong.

### CODE REVIEW

**Comment by stasadev** [comment]
I will test it, the previous attempt to bump `upload-artifact@v4` was not successful:

- #5662

**Review by stasadev — APPROVED** [review]
It works, thank you!

**Comment by rfay** [comment]
They're really putting the pressure on to upgrade now, so I guess we'll try it. We'll back it out if we fail again. I thought there had been a previous attempt.

**Comment by stasadev** [comment]
Tested both changes with #6263

The artifacts are fine and the `mkcert.exe` binary inside `all-ddev-executables.zip` is correct.

**Comment by rfay** [comment]
Thanks!

**Pull request merged**
