### PR TITLE
build: bump docker-compose to v2.25.0

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

docker-compose v2.25.0 was released. Run tests on it.

### CODE REVIEW

**Comment by rfay** [comment]
Wow, completely 100% failed!

**Comment by rfay** [comment]
It seems that the router is broken and is sending the request elsewhere? Maybe some labels are messed up or something.

* Using the 127.0.0.1 URL provided by `ddev start` works fine
* `docker exec -it ddev-router bash` and `curl http://ddev-d10-web` works fine
* Watching logs from `docker logs -f ddev-router` when doing `curl https://d10.ddev.site` gets a 404 and
```
172.24.0.1 - - [07/Mar/2024:00:47:21 +0000] "GET / HTTP/2.0" 404 19 "-" "-" 139 "-" "-" 0ms
```

I think the router is probably trying to hit itself?

Oh, I see, the name resolution is wrong. It's trying to hit 172.24.0.1 for ddev-d10-web, and `ddev-d10-web` actually has the address 172.24.0.3

**Comment by rfay** [comment]
It works fine with docker-compose v2.24.6. `ddev config global --required-docker-compose-version=v2.24.6`

But nothing at all works with 2.24.7. 

Unless it's the networks change in https://github.com/docker/compose/releases/tag/v2.24.7 I don't know what it would be. git bisect may be the path to study it (of compose). Or just wait for issues to show up in their queue?

**Comment by stasadev** [comment]
I tested commits for v2.24.7 docker-compose release.

The bug is somewhere in:

- https://github.com/docker/compose/pull/11556/

**Comment by rfay** [comment]
Thanks for the research!

I think it's actually breaking something about ddev-router/traefik usage.

**Comment by stasadev** [comment]
> Or just wait for issues to show up in their queue?

Yes, found a bug report for this exact problem 😅:

- https://github.com/docker/compose/issues/11589

**Comment by stasadev** [comment]
> I think it's actually breaking something about ddev-router/traefik usage.

Compared the contents of `~/.ddev/.router-compose-full.yaml`:

v2.24.5:

```yaml
networks:
  ddev_default:
    external: true
    name: ddev_default
```

v2.24.7

```yaml
networks:
  ddev_default:
    external: true
    name: ddev_default
  default:
    name: ddev-d10_default
```

and when you start another project:

```yaml
networks:
  ddev_default:
    external: true
    name: ddev_default
  default:
    name: ddev-project_default
```

**Comment by rfay** [comment]
Thanks for the great chasing @stasadev 

Closing this one for now, we'll watch 
* https://github.com/docker/compose/issues/11589

**Comment by stasadev** [comment]
Reopening with rebase and trying to fix our code for docker-compose v2.24.7

**Comment by stasadev** [comment]
There is still a [bug](https://github.com/ddev/ddev/pull/5939#issuecomment-1984037083) with the `default` network, which is created when we are not asked to do so, but this should not prevent the code from running:

**Comment by stasadev** [comment]
It still doesn't work because I made changes in only one place, the fix for the output should be made in:

https://github.com/ddev/ddev/blob/a4bf20b2246790a607b3a0b2fa12e657af5ab796/pkg/ddevapp/compose_yaml.go#L76

**Comment by rfay** [comment]
I guess we should go ahead and go with this? Or should we try to adopt their new format at this time?

**Review by stasadev — APPROVED** [review]
I think we should update docker-compose to v2.25.0.

**Pull request merged**
