### PR TITLE
refactor: avoid calling stop hooks if app is already stopped

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Issue

The stop hooks are even called when the project is already stopped. This can have some negative side effects.

## How This PR Solves The Issue

This patch changes the behavior to only call the stop hooks when the project is not stopped.

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4877"></a>

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
I'm not sure this is appropriate, and neither are you :) When somebody asks for a site to stop, won't they expect hooks to run? 

It's also an unusual case, not sure if it even matters to add code to handle it.

**Comment by stasadev** [comment]
I vote for this PR. I always use a `pre-stop` hook (where I usually clear temporary files).

The current behavior doesn't just run the hooks for the stopped project, *it starts the project, runs all its hooks, and stops the project*.

- When you delete a stopped project, it goes full circle (start, stop) before deleting, it is annoying.
- You can accidentally stop the project twice (unnecessary waste of time).

I think this PR makes sense, tested it and can say it works as it should :+1:

**Review by rfay — APPROVED** [review]
This should be OK, let me know what you think about it now, @gilbertsoft

**Review by rfay — APPROVED** [review]
Seems like this should be OK, thanks.

**Comment by rfay** [comment]
I thought there was an issue about this. Must have been a discord conversation? 

@stasadev could you please test the artifacts in https://github.com/ddev/ddev/pull/4877#issuecomment-1536093968 and see if you get what you want here?

**Review by stasadev — APPROVED** [review]
It works.

1. create a new project
2. add a `pre-stop` hook
3. delete a project

In a stable release, it starts and stops the project before deletion.
With this PR, it immediately deletes the project.

**Comment by rpkoller** [comment]
> I thought there was an issue about this. Must have been a discord conversation?
> 
> @stasadev could you please test the artifacts in [#4877 (comment)](https://github.com/ddev/ddev/pull/4877#issuecomment-1536093968) and see if you get what you want here?

the issue spun off from the following thread on discord: https://discord.com/channels/664580571770388500/1103995259563823198/1103995259563823198

**Comment by stasadev** [comment]
To quickly test this PR:

```
mkdir pr4877 && \
cd pr4877 && \
ddev config --auto --omit-containers=db && \
mkdir -p .ddev/commands/host && \
echo '#!/bin/sh
echo pre-stop' > .ddev/commands/host/pre-stop && \
chmod +x .ddev/commands/host/pre-stop && \
echo "hooks:
    pre-stop:
        - exec-host: ddev pre-stop
" >> .ddev/config.yaml && \
ddev delete --omit-snapshot --yes && \
cd .. && \
rm -rf pr4877
```

Output from this PR (`pre-stop` hook is not called):
```
Creating a new ddev project config in the current directory (/home/user/pr4877) 
Once completed, your configuration will be written to /home/user/pr4877/.ddev/config.yaml
 
Configuring unrecognized codebase as project type 'php' at /home/user/pr4877 
Configuration complete. You may now run 'ddev start'. 
Volume pr4877-mariadb for project pr4877 was deleted 
Volume pr4877-postgres for project pr4877 was deleted 
Volume pr4877_project_mutagen for project pr4877 was deleted 
Project pr4877 was deleted. Your code and configuration are unchanged.
```

Output from the HEAD (`pre-stop` hook is called with the stopped project):
```
Creating a new ddev project config in the current directory (/home/user/pr4877) 
Once completed, your configuration will be written to /home/user/pr4877/.ddev/config.yaml
 
Configuring unrecognized codebase as project of type 'php' at /home/user/pr4877 
Configuration complete. You may now run 'ddev start'. 
 Network ddev-pr4877_default  Created 
 Container ddev-pr4877-web  Created 
 Container ddev-pr4877-web  Started 
 Container ddev-router  Created 
 Container ddev-router  Started 
pre-stop
 Container ddev-pr4877-web  Stopped 
 Container ddev-pr4877-web  Stopped 
 Container ddev-pr4877-web  Removed 
 Network ddev-pr4877_default  Removed 
Volume pr4877-mariadb for project pr4877 was deleted 
Volume pr4877-postgres for project pr4877 was deleted 
Volume pr4877_project_mutagen for project pr4877 was deleted 
Project pr4877 was deleted. Your code and configuration are unchanged.
```

**Pull request merged**
