### PR TITLE
refactor: add -t flag to mailhog call for symfony/mailer native transport compat, fixes #4363

### LINKED ISSUE #4363: Add compatibility between symfony mailer and php sendmail_path configuration for mailhog
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When I configure symfony mailer and set its configuration to "native", trying to send a test email results in an exception from `symfony/mailer`
```
Unsupported sendmail command flags "/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025"; must be one of "-bs" or "-t" but can include additional flags. 
```
Coming from https://github.com/symfony/mailer/blob/6.1/Transport/SendmailTransport.php#L58

I know there is overrides I can do in settings.php so symfony mailer uses the smtp transport on port 1025 but I would like for this to work out of the box without config overrides.

### Describe your solution

Add a `-t` non-functional flag to the command in the php.ini configurations so the exception is not raised.

### Describe alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rodrigoaguilera**
## The Issue

* https://github.com/ddev/ddev/issues/4363

## How This PR Solves The Issue

Add a harmless -t to the mailhog call

## Automated Testing Overview

Mailhog integration is not tested AFAIK and soon will be replaced by mailpit

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5138"></a>

### CODE REVIEW

**Comment by rfay** [comment]
This will require a push of all the images to have any effect, I can do that later, thanks for the PR. 

Please update the manual testing instructions to demonstrate how to sort out that this has solved the problem.

**Comment by rodrigoaguilera** [comment]
Updated steps from the issue:

- `composer create-project drupal/recommended-project mysite`
- `ddev config` with drupal10 options
- `composer req drupal/symfony_mailer:^1@RC`
- Enable the `symfony_mailer` module and send the test email.This works 
Further steps where I found the issue:
- go to transports for the symfony mailer modules `/admin/config/system/mailer/transport` 
- Add the "Native" transport. It requires no configuration, it picks up the `sendmail_path` from the php configuration, in the case of ddev this is `/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025`
- Set the newly native transport as default and try to send a test email
A Drupal error message appears
```
Unsupported sendmail command flags "/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025"; must be one of "-bs" or "-t" but can include additional flags. 
```
the message is not received on mailhog. That error comes from `symfony/mailer`.

**Comment by rfay** [comment]
You didn't give me permissions to push into your forked PR, so please rebase and update with this patch:

```
commit 7180472550f6b2feae0e4d8e0d8d364482ae49c6
Author: Randy Fay <randy@randyfay.com>
Date:   Sun Jul 16 19:25:14 2023 -0600

    Bump WebTag for all the php config changes

diff --git a/pkg/versionconstants/versionconstants.go b/pkg/versionconstants/versionconstants.go
index bc205627f..50428a098 100644
--- a/pkg/versionconstants/versionconstants.go
+++ b/pkg/versionconstants/versionconstants.go
@@ -15,7 +15,7 @@ var AmplitudeAPIKey = ""
 var WebImg = "ddev/ddev-webserver"
 
 // WebTag defines the default web image tag
-var WebTag = "20230707_fix_process_group_kill" // Note that this can be overridden by make
+var WebTag = "20230716_rodrigoaguilera_sendmail_t" // Note that this can be overridden by make
 
 // DBImg defines the default db image used for applications.
 var DBImg = "ddev/ddev-dbserver"
```

Also, please use a good branch name other than "master" for PRs, as that leads to confusion for everybody, and will make a mess next time you want to do a PR. 

Suggestions about branch naming at https://ddev.readthedocs.io/en/latest/developers/building-contributing/#pull-requests-and-pr-preparation

**Comment by rfay** [comment]
Easier just to push it into my fork, so did that. Your commit, so you'll get commit credit. 

Closing in favor of 
* #5151

**Pull request closed without merging**
