### PR TITLE
fix: use natural sort for project+database types, fixes #3561

### LINKED ISSUE #3561: Tidy up order of "Project Type"  and mariadb version suggestions
Recently, I spun a new project and noticed the following long line:

```shell
Project Type [backdrop, drupal10, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress] (laravel): 
```

2 things came to mind:
- "drupal10" should appear after "drupal9"
It reads better.  Is there another sort option that will do this?

- do we need to include "drupal6, drupal7"?
Since these project types are EOL, it don't think we need to _display_ them here. Yes, keep support in DDEV and the documentation; I think the line is too long and removing these will shorten it.

```shell
$ ddev --version
ddev version v1.19.0-alpha3
``

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #3561

## How This PR Solves The Issue

As suggested by @tyler36 , use a "natural sort" on project types, database versions.

## Manual Testing Instructions

```
ddev config --project-type=xxx
ddev config --database=mysql:333
ddev config --database=mariadb:333
ddev config --php-version=333
```

### CODE REVIEW

**Comment by rfay** [comment]
```
gitpod /workspace/junk $ ddev config --project-type=xxx
Creating a new DDEV project config in the current directory (/workspace/junk) 
Once completed, your configuration will be written to /workspace/junk/.ddev/config.yaml
 
Apptype must be one of backdrop, craftcms, django4, drupal6, drupal7, drupal8, drupal9, drupal10, laravel, magento, magento2, php, python, shopware6, silverstripe, typo3, wordpress 
gitpod /workspace/junk $ ddev config --php-version=99
Creating a new DDEV project config in the current directory (/workspace/junk) 
Once completed, your configuration will be written to /workspace/junk/.ddev/config.yaml
 
Configuring a 'php' project with docroot '' at /workspace/junk 
Configuration complete. You may now run 'ddev start'. 
gitpod /workspace/junk $ vi .ddev/config.yaml 
gitpod /workspace/junk $ ddev config --database=mysql:99
You are reconfiguring the project at /workspace/junk.
The existing configuration will be updated and replaced.
Configuring a 'php' project with docroot '' at /workspace/junk
failed to validate config: the junk project has an unsupported database type/version: 'mysql:99', DDEV amd64 only supports the following database types and versions: mariadb: [5.5 10.0 10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.11], mysql: [5.5 5.6 5.7 8.0], postgres: [9 10 11 12 13 14 15 16]
```

**Comment by tyler36** [comment]
Confirmed.

Drupal items appear in "natural" sorted order:  6 -> 10
```shell
$ ddev -v    
ddev version v1.22.7-108-g622227b17

$ ddev config
...
Found a php codebase at /home/user13/code/tmp/laravel. 
Project Type [backdrop, craftcms, django4, drupal6, drupal7, drupal8, drupal9, drupal10, laravel, magento, magento2, php, python, shopware6, silverstripe, typo3, wordpress] (php): 
```

Project config file `./.ddev/config.yaml` lists item in same order

```yaml
# type: <projecttype>  # backdrop, craftcms, django4, drupal6/7/8/9/10, laravel, magento, magento2, php, python, shopware6, silverstripe, typo3, wordpress
```

**Comment by tyler36** [comment]
Note: DDEV docs use _decending_ order

image

**Comment by tyler36** [comment]
Link to #5991 as related PR.

**Review by tyler36 — APPROVED** [review]

**Pull request merged**
