### PR TITLE
refactor: error handling for PR artifact comment [skip ci]

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

PR artifact comment is not created:

- https://github.com/ddev/ddev/actions/runs/9581560892

```
Unhandled error: TypeError: Cannot destructure property 'prNumber' of '(intermediate value)' as it is undefined.
```

## How This PR Solves The Issue

I'm not sure what's wrong here.
I refactored the action to at least better understand the error.

### CODE REVIEW

**Comment by rfay** [comment]
You'll probably have to commit it in master in ddev-test/ddev to be able to see if it works of course.

**Comment by stasadev** [comment]
> You'll probably have to commit it in master in ddev-test/ddev to be able to see if it works of course.

Done.

I tested it here:

- https://github.com/ddev-test/ddev/pull/1

**Review by rfay — APPROVED** [review]
Thanks so much for fixing this so fast!

**Comment by stasadev** [comment]
I ran the PR build again (from the Actions tab) for:

- #6317

It has unrecognized SHA https://github.com/ddev/ddev/actions/runs/9584935394 which I can't find at https://api.github.com/repos/ddev/ddev/pulls

Another thing I noticed, there is not `PR Build` job in #6317 at the bottom.

I can't say for sure, but the last commit was `[skip ci]` and it was force-pushed, maybe it's an edge case that we can't handle.

Let's push #6317 again, but without `[skip ci]`.

**Comment by rfay** [comment]
Sounds OK.

The sha is probably the built-in 
```
${{ secrets.GITHUB_TOKEN }}
```

**Comment by stasadev** [comment]
No, it's this one:

```
${{ github.event.workflow_run.head_sha }}
```

It should match `github.rest.pulls.list[].head.sha` so that the corresponding PR number can be found.

My understanding is that it should just match the last SHA commit, but something went wrong here.

**Pull request merged**
