### PR TITLE
feat: replace fsouza/go-dockerclient with docker/docker/client, fixes #3460

### LINKED ISSUE #3460: Replace fsouza/go-dockerclient with docker/docker/client
[fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient) is barely maintained. We started using it (and it was created) before docker had a golang api.

Replace it with docker/client, see https://docs.docker.com/engine/api/sdk/

An immediate win for this would be the ability to support `ssh://` docker endpoints, which are not supported in go-dockerclient.

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #3460

## How This PR Solves The Issue

Uses `docker/docker/client` instead of `fsouza/go-dockerclient`.

TODO:

- [x] pass all tests.
- [ ] move all `github.com/docker/docker/...` imports to `pkg/dockerutil/dockerutils.go`.
- [ ] deal with Docker context workarounds (maybe not in this PR).

### CODE REVIEW

**Comment by rfay** [comment]
Wow, he DID IT!

**Comment by rfay** [comment]
Great initial news is that trivial manual test works out great, thanks!

**Comment by rfay** [comment]
Getting very close if we're only failing when we get to TestCmdVersion !

**Comment by stasadev** [comment]
The tests are fine, but unfortunately, it's literally impossible to review the changes.
I decided to make two commits: one with the `vendor` folder and the other with everything else.
This way we can easily review the changes (and we can select several commits to review).

[`cbb96e3` (#5787)](https://github.com/ddev/ddev/pull/5787/commits/cbb96e3a666d33ce7fb7053cfdc7f2e31c1ad0a0)

**Review by rfay — APPROVED** [review]
Congratulations on an amazing piece of work, thanks so much!

I think we should get this in as soon as possible so we get maximum experience with it. Just waiting for some sort of stability on master tests right now.

**Pull request merged**
