### PR TITLE
docs: GitHub Codespaces: Adjust examples to make sure docker is running 

### PR DESCRIPTION
**Pull request by eiriksm**
## The Issue
I was trying to follow the guide and something has probably changed in codespaces since then. I found postAttachCommand works though

### CODE REVIEW

**Comment by rfay** [comment]
@mandrasch could you review this please?

**Review by rfay — CHANGES_REQUESTED** [review]
Failed spellcheck due to postAttachCommand

**Comment by mandrasch** [comment]
Hi, thanks for contribution! 

As posted in Discord

- postCreateCommand is the correct event in my opionion
- the devcontainer / codespaces team fixed it previously - docker must be available there, otherwise it's a bug in docker-in-docker on their side (universal image)

So please don't remove this from the docs, it's the correct event to install things on first creation of a codespace (e.g. install scripts, etc.)

Saw this in other codespaces demos as well, they all used postCreate

(Scripts / routines would run twice if postAttach is used and the container is restarted as far as I understand - postCreate is really for the first initial steps on a fresh codespace)

Depends on the use case of course - we could add postAttach to the docs as second option?

Please change PR accordingly if relevant / useful in your opinion :)

Cheers

**Comment by rfay** [comment]
I'm going to change this to draft status for now; @mandrasch if you can keep us up-to-date with the upstream problem it will be appreciated. 
* https://github.com/devcontainers/features/issues/671#issuecomment-1834370756

**Comment by eiriksm** [comment]
Amazing, thanks! 😍

I'm just glad it's nothing wrong with the docs or ddev, so I just agree with everything said in this thread basically

**Comment by mandrasch** [comment]
> Amazing, thanks! 😍
> 
> I'm just glad it's nothing wrong with the docs or ddev, so I just agree with everything said in this thread basically

👍 👍 

just fiy: I submitted a new issue here https://github.com/devcontainers/features/issues/780

**Comment by mandrasch** [comment]
fyi: new comment https://github.com/devcontainers/features/issues/780#issuecomment-1851200127

**Comment by rfay** [comment]
It does sound like perhaps a new approach is in order @mandrasch ? based on 
* https://github.com/devcontainers/features/issues/780#issuecomment-1851200127

**Comment by mandrasch** [comment]
> It does sound like perhaps a new approach is in order @mandrasch ? based on
> 
> * [Docker not available in postCreateCommand (universal image) devcontainers/features#780 (comment)](https://github.com/devcontainers/features/issues/780#issuecomment-1851200127)

yeah... I'll see when I'll find time in the next weeks and I'll post here again. happy travelling in the meantime!

(if anyone else here reading this and wants to try it sooner - please feel free to test the new retry approach 😎)

**Comment by eiriksm** [comment]
Tested the script and slightly altered it. Seems to work ✌️

**Comment by eiriksm** [comment]
Updated with new command suggestion. Removed the inline bash example since that must be considered unstable at this point I guess 🤓✌️

**Comment by mandrasch** [comment]
Awesome work @eiriksm, thanks very much for taking the time to solve this and editing the docs! 👏 🎉  🎉  🎉  

(I'll update https://github.com/mandrasch/ddev-craftcms-vite in the next days or weeks with your new retry logic)

**Comment by mandrasch** [comment]
Works fine for me, good to go from my point of view! 👍 

Thanks very much again! 

One last thing: @eiriksm, could you please change the title of your PR?

**Comment by eiriksm** [comment]
👍done

Thanks for your hard work @mandrasch ♥️

**Comment by stasadev** [comment]
Thank you!

**Pull request merged**
