### PR TITLE
build: bump ddev-php-base and ddev-webserver to base on Debian 12 bookworm, replaces #5278

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

This replaces #5278 - At the time that was done the build didn't succeed, but now it may. 

## How This PR Solves The Issue

Resurrect #5278 

## Manual Testing Instructions

Try it out.

### CODE REVIEW

**Comment by rfay** [comment]
The bookworm ddev-webserver image is about 40MB bigger than bullseye, https://hub.docker.com/r/ddev/ddev-webserver/tags

**Comment by rfay** [comment]
Now we have to think about when it's appropriate to introduce this. Maybe it's no big deal. It's possible it could change some people's Dockerfiles or webimage_extra_packages.

**Comment by rfay** [comment]
Yay, this works!

**Comment by rfay** [comment]
Thanks for pointing out the sources.list change. Sounds *very* positive, what a great idea.

Any thoughts about when we should pull this? I'm thinking that since it doesn't involve docs it could be quite soon, and then we'd discover anything about Bookworm we need to know in the next month or two before release.

**Comment by stasadev** [comment]
I think we can pull it very soon.

**Comment by rfay** [comment]
I'll pull it. Any open PRs with image dependencies will need a new image rebuild.

**Pull request merged**
