### PR TITLE
feat: allow user local commands

### PR DESCRIPTION
**Pull request by claudiu-cristea**
## The Issue

Developers love to create local shorthand commands to run a more sophisticated command or a sequence of commands that they run often but still don't qualify to merged into the project `.ddev/commands` because they are not generic enough

## How This PR Solves The Issue

* User/developers local commands are stored inside `.ddev/local_commands` directory
* The `.ddev/local_commands` directory is not under VCS control.
* The `.ddev/local_commands` directory follows the `.ddev/commands` directory structure and logic.
* In case of collision, user local commands take precedence over project and global commands
* As scope, user local commands are project commands. They are not available globally

## Manual Testing Instructions

Create a command inside `.ddev/local_commands/host` and test the command 

## Automated Testing Overview

Follows the global & project commands logic

## Related Issue Link(s)

None

## Release/Deployment Notes

Still needs documentation

### CODE REVIEW

**Comment by claudiu-cristea** [comment]
I see tests are failing but now idea how to debug & fix. Not a Go guy

**Comment by rfay** [comment]
Hi @claudiu-cristea - I can see two ways to do this just fine without any changes to DDEV:
1. Global commands. They work fine and are under control of the person who is using the machine (unless the team checks in ~/.ddev/commands, I don't know teams that do that, but maybe they're out there.
2. Just gitignore certain things in project .ddev/commands directory using the top-level project gitignore. A team that wanted to follow this practice could just gitignore .ddev/commands/*/*local* or something like that.

**Comment by claudiu-cristea** [comment]
Of course we can do tricks to accomplish that, but...

> Global commands. They work fine and are under control of the person who is using the machine (unless the team checks in ~/.ddev/commands, I don't know teams that do that, but maybe they're out there.

The problem is they are _global_. I was thinking that devs might have project specific commands (I do). Maybe they are used with the same local comand name and scope but with different implementation depending on the project

> Just gitignore certain things in project .ddev/commands directory using the top-level project gitignore. A team that wanted to follow this practice could just gitignore .ddev/commands/*/local or something like that.

Not sure I get this. Does DDEV gather commands from subdirs (e.g.  .ddev/commands/host/local)? I didn't test this but still it still need a "team rule". Not saying it's a big deal but having an out-of-the-box DDEV feature seems better for me

**Comment by rfay** [comment]
> Just gitignore certain things in project .ddev/commands directory using the top-level project gitignore. A team that wanted to follow this practice could just gitignore .ddev/commands/*/local or something like that.

If I understand you correctly, you want custom commands that are *not* under source control, but are specific to a project. 

You can already do this by adding those commands to the project's .gitignore.

But I'm afraid this PR can't succeed as it is, because it hasn't had enough conversation, and it seems to be aimed at meeting a need only of your team and doesn't seem to be fully visualized yet. 

Could you please open an issue that explains exactly what problem you're trying to solve and why you can't do it with current facilities?

I'm going to close this for now, because the conversation has to take place before the implementation. Thanks for the contribution though, and I hope that it works out for everybody and that this got all the thinking going more clearly.

**Pull request closed without merging**
