### PR TITLE
check for empty HTTP_EXPOSE and HTTPS_EXPOSE env variables (traefik only)

### PR DESCRIPTION
**Pull request by hanoii**
See https://discord.com/channels/664580571770388500/1105126065556422737

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4888"></a>

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Looks fine to me, thanks!

**Comment by rfay** [comment]
Please make sure to manually test this and show you results, and tell us how to manually test.

**Comment by hanoii** [comment]
I tried it locally but only by cherry-picking my changes into a local branch out of v1.26.1.

Trying to test on gitpod but for some reasoon is failing to start, getting that the health of the containers cannot be checked. It shouldn't be realted to this, but testing ddev on its own on gitpod too.

Steps would be:

1. Make sure something is listening on port 8983 (`nc -p 8983 -l`?) on the host.
2. ddev init a drupal 9 project (or any other)
3. `ddev get ddev/ddev-drupal9-solr`
4. `ddev start` should fail
5. create a `.ddev/docker-compose.zsolr.yaml` file  with:
```
# Addon overrides
services:
  solr:
    environment:
     - HTTP_EXPOSE=
```
6. `ddev start` should work
7. `docker ps` should show that no port is exposed for solr

**Comment by rfay** [comment]
Please test with the artifacts here (or by building), thanks!

**Comment by hanoii** [comment]
I did test a local build, it work as expected.

**Pull request merged**
