### PR TITLE
docs: improve FAQ - communication between projects

### PR DESCRIPTION
**Pull request by mandrasch**
## The Issue

FAQ https://ddev.readthedocs.io/en/stable/users/usage/faq/#can-different-projects-communicate-with-each-other is a bit hard too read. Everything is in one paragraph

## How This PR Solves The Issue

Use paragraphs, trying to improve readability

## Manual Testing Instructions

https://ddev--6238.org.readthedocs.build/en/6238/users/usage/faq/#can-different-projects-communicate-with-each-other

## Automated Testing Overview

none

### CODE REVIEW

**Comment by rfay** [comment]
There are just a few markdownlint problems here, https://github.com/ddev/ddev/actions/runs/9208669142/job/25331380502

Thanks!

**Comment by mandrasch** [comment]
Ready for review - tried to separate the two use cases (connect to db, connect via http/s) better and make it more readable. Happy to follow your suggestions if this doesn't fit the DDEV docs style! :)

**Review by stasadev — APPROVED** [review]
I changed the formatting for ordered list and used `either/or` instead of just `or`.
I couldn't make a suggestion because I made changes for untouched lines.

**Comment by mandrasch** [comment]
> I changed the formatting for ordered list and used `either/or` instead of just `or`. I couldn't make a suggestion because I made changes for untouched lines.

:+1:

(Ah cool, thanks very much - didn't know how to use the ordered list properly. Without indentation textlint gave me the warning "start with 1." on 2.)

**Review by rfay — APPROVED** [review]
This is fantastic, thanks!

**Pull request merged**
