### PR TITLE
docs: Updates to the quickstarts

### PR DESCRIPTION
**Pull request by rpkoller**
## The Issue
a few changes based on the latest testing

### CODE REVIEW

**Comment by rpkoller** [comment]
but in follow ups pick up on the effort in trying to make the quickstarts more consistent in between CMSes. At the moment some are extremely verbose while others are quite brief, as well as @rfay suggested to standardized the used patterns like how directories are created, how login credentials are specified and so forth. that users are able to recognize the patterns for wayfinding if they go off trail to another CMS

**Comment by rpkoller** [comment]
> * I would prefer `mkdir && cd xxx` for each of these. It just makes them simpler to test.

completely agree, also had that on my radar but thought it would be out of the scope for this issue and should go in a followup. but i can already do it now. the only question. should it be `my_xxxxxxx_project` or `my_xxxxxx_site`?

> * Magento2: Let's break up the setup:install line with backslashes and line breaks:

will do

**Review by rfay — CHANGES_REQUESTED** [review]
This is looking great, and thanks for curating these.

I was hoping for all of the 
```
mkdir my-cakephp-site
cd my-cakephp-site
```

to be changed to `mkdir my-cakephp-site && cd my-cakephp-site`

**Comment by rpkoller** [comment]
> This is looking great, and thanks for curating these.
> 
> I was hoping for all of the
> 
> ```
> mkdir my-cakephp-site
> cd my-cakephp-site
> ```
> 
> to be changed to `mkdir my-cakephp-site && cd my-cakephp-site`

gosh should have read things more thoroughly in the first place. i was fixated onto the naming pattern and totally glossed over the `mkdir && cd xxx` part ... updated. but i left the the quicktarts with git.

**Review by rfay — APPROVED** [review]
Looks great to me, should be ready to go, thanks!

**Comment by rfay** [comment]
Thanks!

**Comment by stasadev** [comment]
I noticed a few more cosmetic changes, created:

- #6107

**Pull request merged**
