### PR TITLE
Add “just simply” link to the writing style guide

### PR DESCRIPTION
**Pull request by mattstein**
This adds an excellent link to the “avoid just and it’s easy” section of the writing style guide that further describes the problem and potential solutions with that sort of language.

Here’s a direct link to it in the preview build: https://ddev--4903.org.readthedocs.build/en/4903/developers/writing-style-guide/#avoid-just-and-easy

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4903"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Let's add a docs check that outlaws "simply".

**Comment by rfay** [comment]
and "just"

**Comment by mattstein** [comment]
Bold! I’ll figure out how to do that.

**Comment by mattstein** [comment]
[Doing this with textlint](https://github.com/ddev/ddev.com-front-end/pull/51) is a matter of adding an npm package and updating the config. I’m trying to avoid adding more dependencies to this project and so far it seems like `pyspelling` and `markdownlint` are both more specialized creatures that aren’t concerned with word usage. Let me know if I’m missing something obvious and I’ll otherwise keep digging!

**Comment by mattstein** [comment]
It looks like I could swap pyspelling for something more comprehensive like [textlint](https://textlint.github.io) or [Vale](https://vale.sh), but with the volume of documentation and the size of the spell check exclusion list it’s going to be a radically different endeavor compared to adding this link.

I tried doing a “quick swap” with Vale and learned there will be no such thing. (Found [another good link](https://css-tricks.com/words-avoid-educational-writing/), though!)

**Comment by rfay** [comment]
It looks like https://github.com/tsuyoshicho/action-textlint would make textlint available, and that action looks maybe a little maintained.

**Review by rfay — APPROVED** [review]
I'm quite sure this will make me stop doing that :)

**Comment by mattstein** [comment]
Vale has a [GitHub Action](https://github.com/errata-ai/vale-action) too. I’d like to bring in either one, but being thorough about it will rival my first PR here! Probably a weeklong adventure that’ll get increasingly uncomfortable if it sits too long.

**Comment by mattstein** [comment]
...so please merge away if you’d like this link. Renovating the documentation linting would be an entirely separate PR.

**Comment by rfay** [comment]
This could also be done with a grep test :) But I think you have more ambitious goals.

**Pull request merged**
