### PR TITLE
[docs] Fix Magento 2 quickstart for Magento 2.4.6, fixes #4762

### LINKED ISSUE #4762: [docs] Magento 2 Quickstart doesn't work "couldn't validate opensearch"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

DDev Debug test file -  https://gist.github.com/bharatk101-dckap/1e66df93732d1da9f7722e2fbfacc437

### Expected Behavior

I installed ddev on my machine and used Magento 2 Quickstart steps to install latest Magento version but I got the error while setting up the magento. Magento setup should complete without any error

### Actual Behavior

image

### Steps To Reproduce

1. Go to ['Magento 2 Quickstart'](https://ddev.readthedocs.io/en/latest/users/quickstart/#magento-2)
2. Run commands step by step
3. Run ddev magento setup command bin/magento setup:install  --db-host=db --db-name=db --db-user=db --db-password=db  --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com  --admin-user=admin --admin-password=admin123 --language=en_US

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cmuench**
- Add elasticsearch engine to options
- Define elasticsearch port
- Disable depending new Magento_AdminAdobeImsTwoFactorAuth module

See issue: #4762 

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4767"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Thanks so much!

**Review by rfay — APPROVED** [review]
Thanks so much, this works for me. I did see a case where the setup directory didn't get created, and `ddev composer install` didn't fix that. Thoughts about what might have happened?

**Comment by cmuench** [comment]
> Thanks so much, this works for me. I did see a case where the setup directory didn't get created, and `ddev composer install` didn't fix that. Thoughts about what might have happened?

Magento ships a base package with the skeleton of the application. All the files in this packages are copied by a Composer Plugin during "Composer Install".
If something breaks during installation the files are not copied. In that case we have to remove the base package from vendor folder and re-run `composer install` which then triggers the copy of the skel again.
The setup directory is part of the base package.

**Comment by rfay** [comment]
So this is a known "issue", and it would have been a result of something (unnoticed) going wrong in `ddev composer create`, and it doesn't get fixed by `ddev composer install`

I would have expected to see an error, but maybe that error doesn't stop execution?

Thanks so much for maintaining the Magento stuff.  I've been thinking about how we can do automated tests of these quickstarts...

**Comment by cmuench** [comment]
@rfay I don't know if most of the people in Magento World are aware of that issue.
At netz98 we developed a "base page redeploy" command for Composer. I already thought to open source that command.
I do not think it's a problem that ddev should fix. We could add a notice to the docs.

**Comment by cmuench** [comment]
@rfay I am just working on a `composer:redeploy-base-packages` command in n98-magerun2 to provide a way to fix this issue.
This will be released with v7.1.0 of n98-magerun2 if tests are successful.
https://github.com/netz98/n98-magerun2/pull/1176

**Pull request merged**
