### PR TITLE
fix: implement limit on number of hosts per line in /etc/hosts because Safari has problems with long lines, fixes #2817

### LINKED ISSUE #2817: One line for each ddev hosts file entry
**Is your feature request related to a problem? Please describe.**
It's not really a problem, more likely an improvement for a faster work flow.

**Describe the solution you'd like**
Currently, ``ddev`` produces entries in ``/etc/hosts`` like this:
```
127.0.0.1 localhost mysite.ddev.site mysecondfqdn.com mythirdsite.org
```
Which are a few steps more if you'd like to go the production site instead of your local machine. The background:
Great online shop systems like Shopware have licensed plugins to a fully qualified domain and they only run in the local instance, if the domain entry matches the fqdn in ``/etc/hosts``.

To make life easier, so for simple commenting out, it would be better to have one fqdn assignment to ``127.0.0.1`` like i. e. vagrant with the pluign ``vagrant-hostmanager`` does on the host machine. It wraps each written entry in an uuid block comment like this, so that the program can clearly identify its written entries based on that vagrant's start id (vagrant generates an hash on each ``vagrant up`` command, which is directly dumped out from that host manager plugin):
```
# some other entries
129.192.202.303

# vagrant-hostmager start-id fec11294-7158-11eb-9439-0242ac130002
127.0.0.1 mysite.ddev.site
127.0.0.1 mysecondsite.ddev.site
127.0.0.1 example.com
127.0.0.1 www.example.com
# vagrant-hostamanger start-id fec11294-7158-11eb-9439-0242ac130002

129.0.2939.3 othersite.com
```

**Describe alternatives you've considered**
Running a local dns server in the LAN like `dnsmasq`, but it's even much more complex and for most developers not really considerable.

**Additional context**
None

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #2817 

I thought we were already limiting the number of hosts per line in /etc/hosts, but it turns out it required extra code.

See https://github.com/goodhosts/hostsfile

## How This PR Solves The Issue

Minor change to goodhosts/hostsfile usage to implement 9-hosts-per-line limit

We may want to wait on this because of non-critical
* https://github.com/goodhosts/hostsfile/issues/51

## Manual Testing Instructions

```
for item in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do 
  sudo ddev hostname a$item.ddev.site 127.0.0.1
done
```

Then inspect hosts file. This needs to be done on macOS, Linux, and traditional Windows.

## Automated Testing Overview

We don't test this behavior I don't think because requires sudo

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4805"></a>

### CODE REVIEW

**Comment by josefglatz** [comment]
# Tested locally with real world /etc/hosts file

## here are the results:

1. ⁇ Broadcast host line was moved to first line (was before on penultimate line)
2. ⁇ IPv6 line `::1 localhost` was moved to 2nd line (was before on last line)
3. ❌ Executing the following test command resulting in a `boardcast line 255.255.255.255` with `a2.ddev.site` 🤨
4. ❤️ All other entries/lines were adopted correct from my POV

**Test command:**

```bash
for item in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do 
  sudo ddev hostname a$item.ddev.site 127.0.0.1
done
```

**Resulting /etc/hosts** under macOS Ventura (project related entries where masked due to privacy)

image

**Comment by rfay** [comment]
Did it really change "broadcast" to "boardcast" ?

I do see this in goodhosts issue queue:
* https://github.com/goodhosts/hostsfile/issues/40

Please link your safari issue with Apple here.

**Comment by rfay** [comment]
For test purposes, here's a plain vanilla starter version of /etc/hosts:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
# End of section
```

**Comment by josefglatz** [comment]
> For test purposes, here's a plain vanilla macOS starter version of /etc/hosts:
> 
> ```
> ##
> # Host Database
> #
> # localhost is used to configure the loopback interface
> # when the system is booting.  Do not change this entry.
> ##
> 127.0.0.1	localhost
> 255.255.255.255	broadcasthost
> ::1             localhost
> # End of section
> ```



> Did it really change "broadcast" to "boardcast" ?
> 
> I do see this in goodhosts issue queue:
> 
> * [HostsPerLine is destructive goodhosts/hostsfile#40](https://github.com/goodhosts/hostsfile/issues/40)
> 
> Please link your safari issue with Apple here.

Sorry, was just a typo. See the screenshot in my comment.

**Comment by rfay** [comment]
Opened 
* https://github.com/goodhosts/hostsfile/issues/42

And created demonstration repository at https://github.com/goodhosts/hostsfile/issues/42

**Comment by rfay** [comment]
Please test with the updated build here. After running the suggested test against a stock macOS hosts file I see
```
255.255.255.255 broadcasthost
::1 localhost

127.0.0.1 a1.ddev.site a10.ddev.site a11.ddev.site a12.ddev.site a13.ddev.site a14.ddev.site a15.ddev.site a2.ddev.site
127.0.0.1 a3.ddev.site a4.ddev.site a5.ddev.site a6.ddev.site a7.ddev.site a8.ddev.site a9.ddev.site localhost
```

Default hosts file is at https://raw.githubusercontent.com/rfay/goodhostsbug/main/hosts

**Comment by rfay** [comment]
@josefglatz if you have trouble again, please provide the starting version of your /etc/hosts so I can experiment with it as well. Thanks!

**Comment by rfay** [comment]
I'm not sure this is going to be an acceptable approach @josefglatz because of the rearranging of the file and loss of comments. Maybe we'll have to wait until something happens with 

* https://github.com/goodhosts/hostsfile/issues/40

However, I'd love it if you could test it anyway...

**Comment by rfay** [comment]
No response from @josefglatz on this at this point, and I'm not very happy about the idea idea of completely rewriting hosts file. Closing for now, happy to reopen and to discuss. I'm following the issue, 
* https://github.com/goodhosts/hostsfile/issues/40

**Comment by josefglatz** [comment]
I tested a little bit. But I can't figure out how to adopt this to make this more bulletproof.

Should we add a note about this in the DDEV documentation @rfay ?

**Comment by rfay** [comment]
You didn't respond on the PR, would have loved to have your input on that. 

I think there's code in there to warn *windows* users, but there's no way to warn safari users.

**Comment by rfay** [comment]
Although 
* https://github.com/goodhosts/hostsfile/issues/42

is being worked on at this point, I'm not sure that
* https://github.com/goodhosts/hostsfile/issues/40

will get attention, but it might!

**Comment by rfay** [comment]
Reopened, as 
* https://github.com/goodhosts/hostsfile/issues/40
is fixed, yay!

**Comment by rfay** [comment]
@josefglatz Please take a look at this again, I think it's working great with the excellent fixes to goodhosts/hostsfile, thanks! Artifacts for testing in https://github.com/ddev/ddev/pull/4805#issuecomment-1783896150

**Review by stasadev — APPROVED** [review]
Tested it on Linux:

```
$ cat /etc/hosts
# Host addresses
127.0.0.1 localhost
127.0.1.1 my-machine-name
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

$ for item in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do sudo ddev hostname a$item.ddev.site 127.0.0.1; done
$ cat /etc/hosts
# Host addresses
127.0.0.1 localhost a1.ddev.site a2.ddev.site a3.ddev.site a4.ddev.site a5.ddev.site a6.ddev.site a7.ddev.site
127.0.0.1 a8.ddev.site a9.ddev.site a10.ddev.site a11.ddev.site a12.ddev.site a13.ddev.site a14.ddev.site a15.ddev.site
127.0.1.1 my-machine-name
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

$ for item in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do sudo ddev hostname -r a$item.ddev.site 127.0.0.1; done
$ cat /etc/hosts
# Host addresses
127.0.0.1 localhost
127.0.1.1 my-machine-name
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by rfay** [comment]
This can now be tested in HEAD, using https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-latest-commits-on-head

**Comment by rfay** [comment]
I also did a prerelease that can be used for testing this, https://github.com/ddev/ddev/releases/tag/v1.22.5-alpha1

**Comment by josefglatz** [comment]
Tested the feature successfully. Sorry for the delay @rfay

**Pull request merged**
