### PR TITLE
ci: reduce Homebrew cleanup

### PR DESCRIPTION
**Pull request by gilbertsoft**
brew upgrade makes too much noise and takes too long, skip for now.

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5088"></a>

### CODE REVIEW

**Comment by gilbertsoft** [comment]
Don't skip ci for this one, we like to have a full run to see if Colima works now.

**Review by rfay — CHANGES_REQUESTED** [review]
It's a mistake that we're not running tests on this. We must have something configured wrong.

**Comment by rfay** [comment]
Oh, it's because the skip ci on the commit itself.

**Comment by rfay** [comment]
Let's remove the skip ci (do another commit) and at least see the tests start to work.

**Pull request merged**
