### PR TITLE
build: show gitpod testing link in PR comment

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

Gitpod long ago stopped showing its badge in a comment on a PR, but we should be able to do it ourselves. 

## How This PR Solves The Issue

Try to add the comment.

### CODE REVIEW

**Comment by rfay** [comment]
I tested this on ddev/ddev-test ( https://github.com/ddev-test/ddev/pull/1 )

and after much work got this:

image

**Review by stasadev — APPROVED** [review]
This is great!

**Comment by tyler36** [comment]
> I tested this on ddev-test/ddev ( https://github.com/ddev-test/ddev/pull/1 )

I assume that repo only produces mac artifacts. DDEV PRs usually show a lot more. (Just checking we didn't disable the others)

image

**Comment by rfay** [comment]
Thanks for paying attention @tyler36 ! There's no change to the artifacts created, if you see one we'll fix right away. I was limiting the loops to make things go faster.

**Comment by tyler36** [comment]
Thank you for confirming @rfay . PR didn't look like it borked anything but was worth the double check. :)

**Comment by rfay** [comment]
Here it is now, https://github.com/ddev/ddev/pull/6002#issuecomment-2011125538

image

**Pull request merged**
