### PR TITLE
docs: Improve WSL2 instructions to explain how to open WSL2 location from vscode on Windows

### PR DESCRIPTION
**Pull request by kiatng**
## The Issue
I added an important step on how to launch VS Code in WSL2. I didn't know about this, I launched it in Windows and couldn't figure out why certain things weren't working correctly. I am using PHP, Intelephense was wreck and spent hours trying different things.

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
There may be a bit more finesse involved here, since these instructions are for all platforms.

In my opinion `code .` in WSL2 is the normal way to launch vscode. But you can also open \\wsl$\Ubuntu\home\... and it should work fine.

**Comment by rfay** [comment]
I tested here and this is actually not correct. I opened a little-used vscode and updated it.  When I opened a project in \\WSL$\Ubuntu\home\rfay\workspace\d10 it prompted me with something like "Are you using WSL? You need to install the WSL support". I did that.  This is explained in https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

I certainly agree that WSL2 adds complexity (and value) to everything, and also agree that using `code .` is the fastest way to get going because it makes these things happen right away. Maybe you can add a commit to tone this down and make it more accurate? Happy to continue the conversation here or in Discord.

image

**Comment by rfay** [comment]
No response from OP, closing. I'm certainly open to adding more about this situation, but I don't think it belongs where this landed, and this one is not correct.

**Comment by kiatng** [comment]
Sorry for not getting back. I revisited ddev again to give it another try. I believe this is a valid PR, I tested it again.

> There may be a bit more finesse involved here, since these instructions are for all platforms.

This PR is specifically for WSL2, the instruction is after line 90 `!!!tip "If you’re using VS Code on Windows with WSL2"`

> In my opinion code . in WSL2 is the normal way to launch vscode. But you can also open \wsl$\Ubuntu\home... and it should work fine.

The above should be documented somewhere but I couldn't find it. That is what this PR is about.

> I tested here and this is actually not correct.

To clarify, for novices not familiar with WSL2 like myself, I always launch VSCode from windows (the incorrect method ), it would launch OK, but Intelephense would be broken. 

image

This PR can potentially saves hours for novices trying to figure out why certain things don't work.

**Comment by rfay** [comment]
I tested with the open-from-vscode method (with the wsl2 extension loaded) and it was fine. 

Please, when people take the time to look at your issue/PR, you can at a minimum respond in a reasonable timeframe.

You're welcome to take another look, and fine-tune your recommendation with a new PR.

**Pull request closed without merging**
