### PR TITLE
feat: use the stable release version as part of the HEAD version on homebrew, fixes #5433

### LINKED ISSUE #5433: `brew install --HEAD` should provide a canonical DDEV/git version, not `vHEAD-<hash>`
In working with 
* #4630, 
* #5379 and 
* #5424

I installed HEAD with `brew unlink ddev && brew install ddev/ddev/ddev --HEAD --fetch-HEAD`. 

I get:
```
# ddev --version
ddev version vHEAD-0ceead6
```

This obviously will bypass any constraint as it's not a valid semver. This is not an important issue I think, just something I saw by chance, however, I wonder how hard would it be for the HEAD version to be something more similar to `v1.22.3-hash` or whatever pre-release scheme you can think best for HEAD. This would at least allow it to work with `ddev_version_constraint`.

### PR DESCRIPTION
**Pull request by hanoii**
I thought about this and I think this will work. I am unsure how to test it though.

I did edit the homebrew formulae locally and and tried adding the version and it works ok.

And out of curiosity, what does COMMIT= do as part of the make? 

Fixes #5433

### CODE REVIEW

**Comment by rfay** [comment]
To test, fork ddev/homebrew-ddev into hanoii/homebrew-ddev and then `brew install --HEAD --fetch-head hanoii/ddev/ddev`

**Comment by hanoii** [comment]
@rfay 

> To test, fork ddev/homebrew-ddev into hanoii/homebrew-ddev and then `brew install --HEAD --fetch-head hanoii/ddev/ddev`

but this would allow me to test editing the formula, not the releasing with gorelease, wouldn't it? I've already tested this by doing `brew edit ddev` and it works ok.

**Comment by rfay** [comment]
I don't actually understand how this can work, can you explain it?

**Comment by hanoii** [comment]
> I don't actually understand how this can work, can you explain it?

Well, my understanding was (and I just checked on https://github.com/ddev/homebrew-ddev/commits/master) is that a new Formulae is pushed to that repo each time a new ddev is released, so I am adding the latest released version to the `VERSION=` used in the make when head is built. It's a go template so `"VERSION=v{{.Version}}-#{version}" would become `"VERSION=v1.23.4-#{version}"` on your next release.

**Comment by hanoii** [comment]
On another note, the wsl2 buildkite is failing since yesterday, it couldn't because of this PR, could it? I restarted it many times, and just did it again.

**Comment by rfay** [comment]
> the wsl2 buildkite is failing since I pushed this, it couldn't because of this PR, could it?

No, and you can just ignore it anyway, since it doesn't test this. (None of the buildkite formulas test it, they just try to shortcut it but sometimes something goes wrong.)

**Comment by hanoii** [comment]
@rfay just double checking you saw https://github.com/ddev/ddev/pull/5438#issuecomment-1768310500

**Comment by hanoii** [comment]
Hi @rfay , just double checking you saw https://github.com/ddev/ddev/pull/5438#issuecomment-1768310500 as well as the comment you replied.

**Comment by rfay** [comment]
I've been traveling the last 3 weeks, this week at Drupalcon Lille, so will eventually catch up. But it would be lovely if you tried it with `brew install --HEAD --fetch-head hanoii/ddev/ddev`

**Comment by hanoii** [comment]
@rfay but trying will not do anything for this PR, as this needs goreleaser to do its thing.. not sure what do you need me to test

**Comment by rfay** [comment]
goreleaser will do exactly what you would do with this recipe in your homebrew fork. If it works there, it's proven to work here. But we can't test goreleaser without a release.

**Comment by rfay** [comment]
Thanks so much for chasing this over multiple PRs and getting it sorted out. 

So the current version would be something like `v1.23-4-HEAD-hash1234`, which is valid, that's good.

The sad thing is that a real version would be `v1.22.3-44-g907fea6e3` (today's HEAD), which would then be comparable to other things properly.

**Review by rfay — CHANGES_REQUESTED** [review]
I did what you suggested here, using rfay/ddev/ddev, and the result is 
```
$ ddev --version
ddev version v{{.Version}}-HEAD-b24f6e5
```

Not at all what we want. 

You can compare with https://github.com/rfay/homebrew-ddev/blob/master/Formula/ddev.rb

and experiment with `brew install --HEAD --fetch-head rfay/ddev/ddev`

**Review by rfay — APPROVED** [review]
Please take a look and see if my commit fixes it for you. I think we just needed to use `make` as-is, without any extras. Not even sure where that may have come from. 

You can test with `brew uninstall -f ddev && brew install --HEAD --fetch-head rfay/ddev/ddev && ddev --version`

**Comment by hanoii** [comment]
> I did what you suggested here, using rfay/ddev/ddev, and the result is

```
$ ddev --version
ddev version v{{.Version}}-HEAD-b24f6e5
Not at all what we want.
```

> You can compare with https://github.com/rfay/homebrew-ddev/blob/master/Formula/ddev.rb

This is what I tried to explain before a few times.. `{{.Version}}` is a go template variable. It's not going to be replaced if you commit it as is to the homebrew Formalue repo. It's **goreleaser** that would replace that string for the release version of the moment. Thus, it would become v1.22.4 the next release and so on. So `{{.Version}}` would never get to the homebrew repo.

> Please take a look and see if my commit fixes it for you. I think we just needed to use make as-is, without any extras. Not even sure where that may have come from.

This may be better, I was worried that homebrew clones the repo singlebranch or something without all of the tags so make would not give the version you expect, but I will try it.

**Comment by hanoii** [comment]
Same way that https://github.com/ddev/ddev/blob/94a62984637f04a43fbe7ed551926db7d821b087/.goreleaser.yml#L147C49-L147C60 works.

**Comment by rfay** [comment]
Ah, so goreleaser is willing to replace it.

But regardless, we just need to go with `make` and it solves everything.

**Comment by hanoii** [comment]
> You can test with brew uninstall -f ddev && brew install --HEAD --fetch-head rfay/ddev/ddev && ddev --version

Yes, this works!

**Comment by rfay** [comment]
So @hanoii you're good with this as it is here? If so we'll get it into v1.22.4-alpha1 release this week and we can more easily test everything about it. Actually, as soon as it's pulled it will be easy to test. So I'll pull when you approve if you do.

**Comment by hanoii** [comment]
@rfay I am good, if there are issues we can revise the previous approach.

**Comment by rfay** [comment]
Thanks for all the work pursuing this! We have a couple of things affecting homebrew in upcoming release, both this and the new autocomplete setup, so we'll try to make sure they both get tested in the alpha. However, I think this one might be testable already.

**Comment by hanoii** [comment]
@rfay FYI, I tested `brew install --HEAD ddev/ddev-edge/ddev` now that alpha was released and it worked as expected!

**Comment by rfay** [comment]
Thanks for testing! I note that the HEAD install doesn't do the autocompletes, but it could, see https://github.com/rfay/homebrew-ddev-edge/commit/7f4933fac2d94eec697a8cc71751abd6d47a642d (which is incomplete, only does bash). `brew install --HEAD` takes just a little longer with that, but might be worth it. Interested in making that work?

**Comment by hanoii** [comment]
it's just copying those lines on the if clause?

**Comment by rfay** [comment]
Yeah, I think that would be it. (Except the other 2-3 completions need to be added)

**Pull request merged**
