### PR TITLE
fix: Build and run with race detection

### PR DESCRIPTION
**Pull request by deviantintegral**
## The Issue

Following up from 
* https://github.com/ddev/ddev/pull/5893. I'd like to see if this shows the race in the logs, and if it shows races anywhere else.

* Check for races in build and test
* Add a full test run (probably later only on master) for the race detection pass
* Update to fix races found

## How This PR Solves The Issue

* Update go.opentelemetry.io for open-telemetry/opentelemetry-go-contrib#4895 (fixes one race)
* Better support in Makefile for race detection (`make CGO_ENABLED=1 BUILDARGS=-race`, `make testpkg CGO_ENABLED=1 TESTARGS=-race`

## Manual Testing Instructions

- [x] Examine test run output
- [x] Try build and test with race detecton

## Automated Testing Overview

Adds `-race` to build and test with race detection

### CODE REVIEW

**Comment by rfay** [comment]
I think the race detected at https://github.com/ddev/ddev/actions/runs/8051021660/job/21987973441?pr=5901

is the exact same one you've fixed in #5893 isn't it? 


```
Write at 0x00c003181ab0 by goroutine 491:
  runtime.racewriterange()
      <autogenerated>:1 +0x24
  internal/poll.ignoringEINTRIO()
      /opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:736 +0x49a
  internal/poll.(*FD).Read()
      /opt/hostedtoolcache/go/1.22.0/x64/src/internal/poll/fd_unix.go:160 +0x1e5
  os.(*File).read()
      /opt/hostedtoolcache/go/1.22.0/x64/src/os/file_posix.go:29 +0xac
  os.(*File).Read()
      /opt/hostedtoolcache/go/1.22.0/x64/src/os/file.go:118 +0x89
  bufio.(*Scanner).Scan()
      /opt/hostedtoolcache/go/1.22.0/x64/src/bufio/scan.go:219 +0x13e1
  github.com/ddev/ddev/pkg/dockerutil.ComposeCmd.func1()
      /home/runner/work/ddev/ddev/pkg/dockerutil/dockerutils.go:666 +0x84

Previous read at 0x00c003181ab3 by goroutine 484:
  runtime.slicecopy()
      /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/slice.go:325 +0x0
  bytes.(*Buffer).Write()
      /opt/hostedtoolcache/go/1.22.0/x64/src/bytes/buffer.go:181 +0x118
  github.com/ddev/ddev/pkg/dockerutil.ComposeCmd()
      /home/runner/work/ddev/ddev/pkg/dockerutil/dockerutils.go:687 +0x110b
  github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).Start()
      /home/runner/work/ddev/ddev/pkg/ddevapp/ddevapp.go:1253 +0x3c04
  github.com/ddev/ddev/pkg/ddevapp_test.TestPostgresConfigOverride()
      /home/runner/work/ddev/ddev/pkg/ddevapp/config_test.go:922 +0x5b7
  testing.tRunner()
      /opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1742 +0x44
```

We're going to get lots of value out of your long expedition here! Thanks so much.

**Comment by deviantintegral** [comment]
🤦 here I am running tests locally, and I just needed to scroll up more.

I'll merge that PR here and see how far it gets!

**Comment by rfay** [comment]
I imagine we'll want to turn off the fail-fast to get a real review of this. I'm thinking we should just create a new separate test that does this regularly.

**Comment by rfay** [comment]
Rebased to get the new upstream with the fix in it.

**Comment by deviantintegral** [comment]
I went to reproduce this locally and found another race with mutagen. I was expecting the above race to happen though, so I'm surprised it isn't.

```
Starting Mutagen sync process...
....==================
WARNING: DATA RACE
Write at 0x00c001b9e290 by goroutine 58:
  github.com/ddev/ddev/pkg/ddevapp.CreateOrResumeMutagenSync.func1()
      /Users/andrew/workspace/no-arq-backup/ddev/pkg/ddevapp/mutagen.go:227 +0x68

Previous write at 0x00c001b9e290 by goroutine 59:
  github.com/ddev/ddev/pkg/ddevapp.CreateOrResumeMutagenSync.func2()
      /Users/andrew/workspace/no-arq-backup/ddev/pkg/ddevapp/mutagen.go:243 +0xf4

Goroutine 58 (running) created at:
  github.com/ddev/ddev/pkg/ddevapp.CreateOrResumeMutagenSync()
      /Users/andrew/workspace/no-arq-backup/ddev/pkg/ddevapp/mutagen.go:226 +0xc64
  github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).Start()
      /Users/andrew/workspace/no-arq-backup/ddev/pkg/ddevapp/ddevapp.go:1340 +0x3724
  github.com/ddev/ddev/cmd/ddev/cmd.init.func57()
      /Users/andrew/workspace/no-arq-backup/ddev/cmd/ddev/cmd/start.go:136 +0xbdc
  github.com/spf13/cobra.(*Command).execute()
      /Users/andrew/workspace/no-arq-backup/ddev/vendor/github.com/spf13/cobra/command.go:987 +0xc24
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/andrew/workspace/no-arq-backup/ddev/vendor/github.com/spf13/cobra/command.go:1115 +0x4b8
  github.com/spf13/cobra.(*Command).Execute()
      /Users/andrew/workspace/no-arq-backup/ddev/vendor/github.com/spf13/cobra/command.go:1039 +0x34
  github.com/ddev/ddev/cmd/ddev/cmd.Execute()
      /Users/andrew/workspace/no-arq-backup/ddev/cmd/ddev/cmd/root.go:162 +0x20
  main.main()
      /Users/andrew/workspace/no-arq-backup/ddev/cmd/ddev/main.go:27 +0x3d0

Goroutine 59 (running) created at:
  github.com/ddev/ddev/pkg/ddevapp.CreateOrResumeMutagenSync()
      /Users/andrew/workspace/no-arq-backup/ddev/pkg/ddevapp/mutagen.go:237 +0xdac
  github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).Start()
      /Users/andrew/workspace/no-arq-backup/ddev/pkg/ddevapp/ddevapp.go:1340 +0x3724
  github.com/ddev/ddev/cmd/ddev/cmd.init.func57()
      /Users/andrew/workspace/no-arq-backup/ddev/cmd/ddev/cmd/start.go:136 +0xbdc
  github.com/spf13/cobra.(*Command).execute()
      /Users/andrew/workspace/no-arq-backup/ddev/vendor/github.com/spf13/cobra/command.go:987 +0xc24
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/andrew/workspace/no-arq-backup/ddev/vendor/github.com/spf13/cobra/command.go:1115 +0x4b8
  github.com/spf13/cobra.(*Command).Execute()
      /Users/andrew/workspace/no-arq-backup/ddev/vendor/github.com/spf13/cobra/command.go:1039 +0x34
  github.com/ddev/ddev/cmd/ddev/cmd.Execute()
      /Users/andrew/workspace/no-arq-backup/ddev/cmd/ddev/cmd/root.go:162 +0x20
  main.main()
      /Users/andrew/workspace/no-arq-backup/ddev/cmd/ddev/main.go:27 +0x3d0
==================
```

**Comment by rfay** [comment]
The race described in https://github.com/ddev/ddev/pull/5901#issuecomment-1977475931 is a a result of pathological behavior where CreateOrResumeMutagenSync() is being called by itself in a separate goroutine. 

* In https://github.com/ddev/ddev/blob/e5e0238fd395ee45f3494df5ae56157568ffed05/pkg/ddevapp/mutagen.go#L243 it does an app.Start()
* The app.Start() does a CreateOrResumeMutagenSync() in https://github.com/ddev/ddev/blob/4928230143fa6a271ed6d38fd0a266f64307e021/pkg/ddevapp/ddevapp.go#L1340

**Comment by deviantintegral** [comment]
@rfay I doubt I'll be able to push this along in the near-term, so feel free to take it over.

**Comment by rfay** [comment]
Yes, I'm working on it and will get a regular test running on push to master.

**Comment by rfay** [comment]
https://github.com/ddev/ddev/actions/runs/8297282124/job/22708072875?pr=5901#step:17:1394
```
==================
WARNING: DATA RACE
Read at 0x00c0000c6468 by goroutine 209:
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Transport).RoundTrip()
 ```

* https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4895

**Pull request merged**
