### PR TITLE
fix: add correct mimetype for xsl and xslt, fixes #5457

### LINKED ISSUE #5457: Incorrect content-type header for XSL files in nginx-fpm image
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Running bash [-c /var/folders/6m/mbmq3pwx10v1b4jj3t44tsk80000gn/T/test_ddev.sh]
======= Existing project config =========
These config files were loaded for project jfklibrary: [/Users/agarzola/projects/jfkl/.ddev/config.yaml]
name: jfklibrary
type: drupal9
docroot: docroot
php_version: 8.1
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.22.3
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.5}
webimage_extra_packages: [chromium libxslt1-dev]
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-22214 in ../tryddevproject-22214 =========
OS Information: Darwin vonnegut.lan 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
ProductName:            macOS
ProductVersion:         13.1
BuildVersion:           22C65
User information: uid=501(agarzola) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae),701(com.apple.sharepoint.group.1),702(com.apple.sharepoint.group.2)
DDEV version:  ITEM             VALUE
 DDEV version     v1.22.3
 architecture     arm64
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.3
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.3
 docker           20.10.22
 docker-compose   v2.21.0
 docker-platform  docker-desktop
 mutagen          0.17.2
 os               darwin
 router           ddev/ddev-traefik-router:v1.22.3
 web              ddev/ddev-webserver:v1.22.3
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=mutagen
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.21.0
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443
mailpit-http-port=8025
mailpit-https-port=8026
traefik-monitor-port=10999

======= DOCKER info =========
docker location: lrwxr-xr-x  1 root  staff  54 Aug  4  2021 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
Docker Desktop Version: Docker Desktop for Mac 4.16.2 build 95914
docker version:
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.17.2
--------------------------------------------------------------------------------
Name: drupal-contrib
Identifier: sync_a5MSMLDxToWHigrl0g9sVx2P4ocJ3EarkXdlq9L9lvR
Labels:
        com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
        com.ddev.volume-signature: var-run-1696017118
Configuration:
        Synchronization mode: Two Way Resolved
        Hashing algorithm: Default (SHA-1)
        Maximum allowed entry count: Default (2⁶⁴−1)
        Maximum staging file size: Default (18 EB)
        Symbolic link mode: POSIX Raw
        Ignore VCS mode: Default (Propagate)
        Ignores:
                /.git
                /.tarballs
                /.ddev/db_snapshots
                /.ddev/.importdb*
                .DS_Store
                .idea
                /web/sites/default/files
        Permissions mode: Default (Portable)
Alpha:
        URL: /Users/agarzola/projects/drupal-contrib
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
        Connected: Yes
        Synchronizable contents:
                10019 directories
                51127 files (269 MB)
                121 symbolic links
Beta:
        URL: docker://ddev-drupal-contrib-web/var/www/html
                DOCKER_HOST=unix:///var/run/docker.sock
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
                Compression: Default (DEFLATE)
        Connected: Yes
        Synchronizable contents:
                10019 directories
                51127 files (269 MB)
                121 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
Name: jfklibrary
Identifier: sync_xnptbh9tCcbUhLNWVduqeyG2La7nfqesdpe2vVY6DjG
Labels:
        com.ddev.config-hash: 654a7799e053320033f4baa45c0f9c345f2546e4
        com.ddev.volume-signature: var-run-1696350722
Configuration:
        Synchronization mode: Two Way Resolved
        Hashing algorithm: Default (SHA-1)
        Maximum allowed entry count: Default (2⁶⁴−1)
        Maximum staging file size: Default (18 EB)
        Symbolic link mode: POSIX Raw
        Ignore VCS mode: Default (Propagate)
        Ignores:
                /.git
                /.tarballs
                /.ddev/db_snapshots
                /.ddev/.importdb*
                .DS_Store
                .idea
                /docroot/sites/default/files
        Permissions mode: Default (Portable)
Alpha:
        URL: /Users/agarzola/projects/jfkl
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
        Connected: Yes
        Synchronizable contents:
                20311 directories
                92597 files (3.1 GB)
                162 symbolic links
Beta:
        URL: docker://ddev-jfklibrary-web/var/www/html
                DOCKER_HOST=unix:///var/run/docker.sock
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
                Compression: Default (DEFLATE)
        Connected: Yes
        Synchronizable contents:
                20311 directories
                92597 files (3.1 GB)
                162 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
Name: imprivata
Identifier: sync_Rbggc3qdxFg1nUWoVIwW98ZkLNdDOoH9NacFj9yiWqp
Labels:
        com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
        com.ddev.volume-signature: var-run-1696936737
Configuration:
        Synchronization mode: Two Way Resolved
        Hashing algorithm: Default (SHA-1)
        Maximum allowed entry count: Default (2⁶⁴−1)
        Maximum staging file size: Default (18 EB)
        Symbolic link mode: POSIX Raw
        Ignore VCS mode: Default (Propagate)
        Ignores:
                /.git
                /.tarballs
                /.ddev/db_snapshots
                /.ddev/.importdb*
                .DS_Store
                .idea
                /web/sites/default/files
        Permissions mode: Default (Portable)
Alpha:
        URL: /Users/agarzola/projects/imprivata-drupal-8
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
        Connected: Yes
        Synchronizable contents:
                17333 directories
                86133 files (526 MB)
                190 symbolic links
Beta:
        URL: docker://ddev-imprivata-web/var/www/html
                DOCKER_HOST=unix:///var/run/docker.sock
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
                Compression: Default (DEFLATE)
        Connected: Yes
        Synchronizable contents:
                17333 directories
                86133 files (526 MB)
                190 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
Name: benz-platform
Identifier: sync_19UIeSfX3mjYRmoGEA3i3dIPpE5Ug4qPTVdcxvXLfvz
Labels:
        com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
        com.ddev.volume-signature: var-run-1696937604
Configuration:
        Synchronization mode: Two Way Resolved
        Hashing algorithm: Default (SHA-1)
        Maximum allowed entry count: Default (2⁶⁴−1)
        Maximum staging file size: Default (18 EB)
        Symbolic link mode: POSIX Raw
        Ignore VCS mode: Default (Propagate)
        Ignores:
                /.git
                /.tarballs
                /.ddev/db_snapshots
                /.ddev/.importdb*
                .DS_Store
                .idea
                /web/sites/default/files
        Permissions mode: Default (Portable)
Alpha:
        URL: /Users/agarzola/projects/benz-platform
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
        Connected: Yes
        Synchronizable contents:
                18782 directories
                84880 files (814 MB)
                324 symbolic links
Beta:
        URL: docker://ddev-benz-platform-web/var/www/html
                DOCKER_HOST=unix:///var/run/docker.sock
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
                Compression: Default (DEFLATE)
        Connected: Yes
        Synchronizable contents:
                18790 directories
                84916 files (815 MB)
                324 symbolic links
Conflicts:
        (alpha) node_modules/anymatch/node_modules/micromatch (Directory -> <non-existent>)
        (beta)  node_modules/anymatch/node_modules/micromatch/lib/.DS_Store (<non-existent> -> Untracked content)

        (alpha) node_modules/glob-watcher/node_modules/micromatch (Directory -> <non-existent>)
        (beta)  node_modules/glob-watcher/node_modules/micromatch/lib/.DS_Store (<non-existent> -> Untracked content)

        (alpha) node_modules/liftoff/node_modules/micromatch (Directory -> <non-existent>)
        (beta)  node_modules/liftoff/node_modules/micromatch/lib/.DS_Store (<non-existent> -> Untracked content)

        (alpha) node_modules/matchdep/node_modules/micromatch (Directory -> <non-existent>)
        (beta)  node_modules/matchdep/node_modules/micromatch/lib/.DS_Store (<non-existent> -> Untracked content)
Status: Watching for changes
--------------------------------------------------------------------------------
======= Docker Info =========
Docker platform: docker-desktop
Using Docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.21.0
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 20.10.22
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 975.1G    145.4G    780.1G  16% /

 Container ddev-benz-platform-redis  Stopped
 Container ddev-benz-platform-db  Stopped
 Container ddev-benz-platform-web  Stopped
 Container ddev-benz-platform-redis  Stopped
 Container ddev-benz-platform-web  Stopped
 Container ddev-benz-platform-db  Stopped
 Container ddev-benz-platform-redis  Removed
 Container ddev-benz-platform-db  Removed
 Container ddev-benz-platform-web  Removed
 Network ddev-benz-platform_default  Removed
Project benz-platform has been stopped.
 Container ddev-drupal-contrib-db  Stopped
 Container ddev-drupal-contrib-web  Stopped
 Container ddev-drupal-contrib-chromedriver  Stopped
 Container ddev-drupal-contrib-db  Stopped
 Container ddev-drupal-contrib-web  Stopped
 Container ddev-drupal-contrib-db  Removed
 Container ddev-drupal-contrib-web  Removed
 Container ddev-drupal-contrib-chromedriver  Stopped
 Container ddev-drupal-contrib-chromedriver  Removed
 Network ddev-drupal-contrib_default  Removed
Project drupal-contrib has been stopped.
 Container ddev-imprivata-redis  Stopped
 Container ddev-imprivata-db  Stopped
 Container ddev-imprivata-solr  Stopped
 Container ddev-imprivata-web  Stopped
 Container ddev-imprivata-db  Stopped
 Container ddev-imprivata-web  Stopped
 Container ddev-imprivata-solr  Stopped
 Container ddev-imprivata-redis  Stopped
 Container ddev-imprivata-solr  Removed
 Container ddev-imprivata-redis  Removed
 Container ddev-imprivata-db  Removed
 Container ddev-imprivata-web  Removed
 Network ddev-imprivata_default  Removed
Project imprivata has been stopped.
 Container ddev-jfklibrary-memcached  Stopped
 Container ddev-jfklibrary-db  Stopped
 Container ddev-jfklibrary-web  Stopped
 Container ddev-jfklibrary-db  Stopped
 Container ddev-jfklibrary-web  Stopped
 Container ddev-jfklibrary-memcached  Stopped
 Container ddev-jfklibrary-memcached  Removed
 Container ddev-jfklibrary-db  Removed
 Container ddev-jfklibrary-web  Removed
 Network ddev-jfklibrary_default  Removed
Project jfklibrary has been stopped.
Stopped Mutagen daemon
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers:
CONTAINER ID   IMAGE                                         COMMAND                  CREATED        STATUS                      PORTS                                                                   NAMES
50ad2c4e7834   bitnami/mariadb:10.5.8-debian-10-r74          "/lando-entrypoint.s…"   3 weeks ago    Exited (137) 3 weeks ago                                                                            jfklibrary_database_1
120e9ceb304f   devwithlando/php:8.1-apache-4                 "/lando-entrypoint.s…"   3 weeks ago    Exited (137) 3 weeks ago                                                                            jfklibrary_appserver_1
8a751fabf78a   bitnami/memcached:1.6.1-debian-10-r4          "/lando-entrypoint.s…"   3 weeks ago    Exited (137) 3 weeks ago                                                                            jfklibrary_cache_1
b11568cc12f6   node:16                                       "/lando-entrypoint.s…"   3 weeks ago    Exited (137) 3 weeks ago                                                                            jfklibrary_theme_1
a5cab14dd6e5   traefik:2.2.0                                 "/lando-entrypoint.s…"   4 weeks ago    Exited (137) 3 weeks ago                                                                            landoproxyhyperion5000gandalfedition_proxy_1
be92921dda3c   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_rivian_1
b97667749347   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_showcase_1
087b148e17ad   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_bertelsmann_1
dd208ce4222b   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_seagate_1
fb2ed7d9f8df   redis:7                                       "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_cache_1
a922e3807046   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_levis_1
dc9184ceaa70   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_lam_1
5f30c04fb379   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_synopsys_1
5ed268c0f164   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_gen_1
37d25aee964a   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_autodesk_1
7511e90a01bd   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_uc_1
72f884b2eeb8   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_stripe_1
24d5b0e7b02f   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_common_1
c671fee755df   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_honeywell_1
c4445e93058f   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_bae_1
d9fd1c012768   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_paypal_1
5a4e1bf6492b   bitnami/mariadb:10.3.27-debian-10-r84         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_database_1
3db24ff47907   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_splunk_1
2669fdad792d   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_intuit_1
3a59e811fb07   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_beigene_1
97052b7cd55f   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_okta_1
5444fd2c9c49   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_adobe_1
c1a12740736e   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_csl_1
a29856d45fa5   bitnami/mariadb:10.11                         "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_workday_1
2f7c18c481c4   phpmyadmin/phpmyadmin:5.1.1                   "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_pma_1
fafe86a93f0f   devwithlando/php:8.2-apache-4                 "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_appserver_1
622f8b6b35e8   node:18                                       "/lando-entrypoint.s…"   3 months ago   Exited (137) 3 months ago                                                                           benzplatform_node_1
76e2be0e5ddf   bitnami/mysql:5.7.29-debian-10-r51            "/lando-entrypoint.s…"   5 months ago   Exited (137) 5 months ago                                                                           drupaltest_database_1
0f5893aa9e7e   drupalci/webdriver-chromedriver:production    "/lando-entrypoint.s…"   5 months ago   Exited (137) 5 months ago                                                                           drupaltest_chrome_1
6d55fefc5425   devwithlando/php:8.1-apache-4                 "/lando-entrypoint.s…"   5 months ago   Exited (137) 5 months ago                                                                           drupaltest_appserver_1
08d6e732bf91   bitnami/nginx:1.17.10-debian-10-r52           "/lando-entrypoint.s…"   6 months ago   Exited (255) 5 months ago   8080/tcp, 8443/tcp, 127.0.0.1:32777->80/tcp, 127.0.0.1:32776->443/tcp   apipoets_appserver_nginx_1
649c36edff5c   solr:8                                        "/lando-entrypoint.s…"   6 months ago   Exited (255) 5 months ago   127.0.0.1:32775->8983/tcp                                               apipoets_search_1
4f93cbf7ddb3   bitnami/mariadb:10.3.27-debian-10-r84         "/lando-entrypoint.s…"   6 months ago   Exited (255) 5 months ago   127.0.0.1:32771->3306/tcp                                               apipoets_database_1
088bb1d584f0   mailhog/mailhog:v1.0.1                        "/lando-entrypoint.s…"   6 months ago   Exited (255) 5 months ago   1025/tcp, 8025/tcp, 127.0.0.1:32772->80/tcp                             apipoets_mailhog_1
60e7e0a24bbd   redis:5                                       "/lando-entrypoint.s…"   6 months ago   Exited (255) 5 months ago   6379/tcp                                                                apipoets_cache_1
9856d582733d   devwithlando/php:8.1-fpm-4                    "/lando-entrypoint.s…"   6 months ago   Exited (255) 5 months ago   9000/tcp                                                                apipoets_appserver_1
3f1d1f1853e3   857fd9d35cb7                                  "/lando-entrypoint.s…"   6 months ago   Exited (255) 5 months ago                                                                           apipoets_node_1
b0d80befaf48   857fd9d35cb7                                  "/lando-entrypoint.s…"   6 months ago   Exited (255) 5 months ago   127.0.0.1:32774->443/tcp, 127.0.0.1:32773->6006/tcp                     apipoets_storybook_1
6388feb676fa   bitnami/mysql:5.7.29-debian-10-r51            "/lando-entrypoint.s…"   7 months ago   Exited (137) 7 months ago                                                                           drupalcontributions_database_1
d361464ba27b   seleniarm/standalone-chromium:102.0.5005.61   "/lando-entrypoint.s…"   7 months ago   Exited (137) 7 months ago                                                                           drupalcontributions_chrome_1
11b99a03a4bd   36465d3622b6                                  "/lando-entrypoint.s…"   7 months ago   Exited (137) 7 months ago                                                                           drupalcontributions_appserver_1
a07a04a144ff   bitnami/mysql:5.7.29-debian-10-r51            "/lando-entrypoint.s…"   7 months ago   Exited (137) 7 months ago                                                                           drupaldev_database_1
1b1da0d8d3ea   drupalci/webdriver-chromedriver:production    "/lando-entrypoint.s…"   7 months ago   Exited (137) 7 months ago                                                                           drupaldev_chrome_1
7f0fb76489e4   36465d3622b6                                  "/lando-entrypoint.s…"   7 months ago   Exited (137) 7 months ago                                                                           drupaldev_appserver_1
Network ddev_default created

 TIP OF THE DAY
 `ddev npm` is the right way to run npm commands in your web container.

Starting tryddevproject-22214...
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
 Network ddev-tryddevproject-22214_default  Created
 Container ddev-tryddevproject-22214-web  Created
 Container ddev-tryddevproject-22214-db  Created
 Container ddev-tryddevproject-22214-db  Started
 Container ddev-tryddevproject-22214-web  Started
You have Mutagen enabled and your 'php' project type doesn't have `upload_dirs` set.
For faster startup and less disk usage, set upload_dirs to where your user-generated files are stored.
If this is intended you can disable this warning with `ddev config --disable-upload-dirs-warning`.
Starting Mutagen sync process... This can take some time.
Mutagen sync flush completed in 2s.
For details on sync status 'ddev mutagen st tryddevproject-22214 -l'
 Container ddev-router  Created
 Container ddev-router  Started
Successfully started tryddevproject-22214
Project can be reached at https://tryddevproject-22214.ddev.site https://127.0.0.1:53463
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 24 Oct 2023 21:17:18 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-22214.ddev.site from outside:
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Tue, 24 Oct 2023 21:17:18 GMT
Server: nginx
Vary: Accept-Encoding

======== full curl of http://tryddevproject-22214.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-22214'
======== Project ownership on host:
drwxr-xr-x  4 agarzola  staff  128 Oct 24 17:15 ../tryddevproject-22214
======== Project ownership in container:
drwxr-xr-x 4 agarzola dialout 4096 Oct 24 21:17 /var/www/html
======== In-container filesystem:
Filesystem     Type  1K-blocks      Used Available Use% Mounted on
/dev/vda1      ext4 1022420372 152115248 818335724  16% /var/www
======== curl again of tryddevproject-22214 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-22214'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds

Please run cleanup after debugging with 'ddev debug testcleanup'

```
</details>         

### Expected Behavior

curl -i "https://mysite.ddev.site/stylesheet.xsl" | grep content-type
content-type: application/xslt+xml

### Actual Behavior

curl -i "https://mysite.ddev.site/stylesheet.xsl" | grep content-type
content-type: application/octet-stream

The mimetype is incorrect for XSL files and will break the ability to process XSL from an XML file that includes it. 

### Steps To Reproduce

1. Create an XML file in your document root. 
2. Create an XSL stylesheet for that XML document. 
3. Load the XML file. XSL will not process. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by apotek**
Add correct mimetype for xsl and xslt

Resolves: #5457

## The Issue
XSL and XSLT files are being served by nginx with the default mimetype (application/octet-stream instead of [the standard](https://www.w3.org/TR/xslt20/#media-type-registration) `application/xslt+xml`.

This means that the `content-type` header is sending the wrong application type to the XSLT parser/transformer application and it therefore fails to process. 

## How This PR Solves The Issue
This code change ~~overrides the shipping debian /etc/nginx/mime.types with our own ddev-managed /etc/nginx/mime.types file so we can more easily make fixes to the mime types while waiting for the upstream distro to be updated.~~ adds a `types{}` section to the nginx.conf just under the `include mime.types` directive where we can add custom mimetypes for ddev.

## Manual Testing Instructions
1. Build your ddev instance
2. Put an XSL file such as /test.xsl in the document root. 
3. `curl -is "https://yoursite.ddev.site/test.xsl" | grep content-type`
You should see `content-type: application/xslt+xml` in the output.

## Automated Testing Overview
No tests added. Is there a framework for scripting a test for this in ddev? I read through [the testing docs](https://github.com/ddev/ddev/blob/master/docs/content/developers/building-contributing.md#testing) but that all surrounds tests for ddev itself. Please let me know if there is a recommended way I can create a test for this.

## Related Issue Link(s)
https://github.com/ddev/ddev/issues/5457

## Release/Deployment Notes
This does not affect the behavior of other parts of ddev itself.

If a user's application relies on a non-standards-compliant content-type mimetype for .xsl / .xslt files, their application may fail, as we are now serving .xsl and .xslt files according to W3 standards.

This merge request sponsored by [Chromatic](https://chromatichq.com/).

### CODE REVIEW

**Comment by rfay** [comment]
This will still need a custom image tag pushed, we'll work on that. 

Were you able to manually test it by changing /etc/nginx/mime.types?

**Comment by apotek** [comment]
> Were you able to manually test it by changing /etc/nginx/mime.types?

After starting my ddev test project, I executed `ddev ssh -s web` and manually edited /etc/nginx/nginx.conf to add exactly what the _latest_ commit does, viz:

```diff
include mime.types
+ types {
+   application/xslt+xml xsl xslt;
+ }
```
After kicking nginx, I get this:

> curl -i -k "https://mysite.ddev.site/testxsl.xsl"
> HTTP/2 200 
> accept-ranges: bytes
> content-type: application/xslt+xml

Which is what we wanted.

**Comment by rfay** [comment]
Thank you!

**Comment by apotek** [comment]
> I'm quite sure we'll be successful getting this into DDEV core, perhaps a point release in November. I should note that in the meantime you can just use a .ddev/web-build/Dockerfile to add the file. Just put the mime.types in .ddev/web-build and I think this would work for the Dockerfile:

Thank you. That's a lot simpler than what I was doing 😓 

> Thanks for your thoughtful approach to testing solving this, and for the PR! Are you going to try to get it in upstream?

https://trac.nginx.org/nginx/ticket/2552
https://salsa.debian.org/nginx-team/nginx/-/merge_requests/78

**Comment by rfay** [comment]
Impressive!

**Comment by rfay** [comment]
Pushed a tagged image for this feature, updated the tag DDEV uses, and rebased. 

Please test manually @apotek , thanks!

**Comment by rfay** [comment]
It looks to me like it's working:
```
$ curl -I https://d10.ddev.site/test.xsl
HTTP/2 200
accept-ranges: bytes
content-type: application/xslt+xml
date: Mon, 30 Oct 2023 23:39:39 GMT
etag: "65403e0e-29c"
last-modified: Mon, 30 Oct 2023 23:36:46 GMT
server: nginx
content-length: 668
```

**Review by rfay — APPROVED** [review]
Looks ok to me, tests ok, will look forward to your manual test results. Make sure to remove any custom Dockerfile that you may be using...

**Comment by apotek** [comment]
> Please test manually @apotek , thanks!

Thank you @rfay . I read the docs and honestly am unsure of what to do  in order to test this. Since this PR does not modify `ddev` itself, it doesn't seem I would need to use the custom binaries. What I need is to build the nginx docker service image from my merge request's source directory (which I guess would be running make in my ddev repo directory) and then, somehow, be able to use that image when I run `ddev start`. That's the part I am unsure of.

Can I somehow change 

```
webserver_type: nginx-fpm
```

to point to my locally generated nginx-fpm container?

I apologize if this should be obvious to me or if I am missing something. 

I did read https://ddev.readthedocs.io/en/latest/developers/building-contributing/#making-changes-to-ddev-images and https://ddev.readthedocs.io/en/latest/developers/building-contributing/#making-changes-to-ddev-images several times.  I don't think I would want to push my built image, since I don't want to publish it either to the ddev docker account or my own. I just want to use the built image locally. So that's where I am getting confused.

**Comment by rfay** [comment]
All you have to do is download the ddev artifacts from this PR, you don't have to build anything. And use them. Unzip ddev, follow the instructions, put it in your path or explicitly path it.  Then use it in your project. If that doesn't make any sense I'll be happy to do a screenshare call with you, come on over to Discord or whatever, https://discord.gg/hCZFfAMc5k 

There is nothing you have to do with DDEV images. I pushed the changed image for you. All you need to use is the updated DDEV in this PR, https://github.com/ddev/ddev/pull/5458#issuecomment-1786177740 - It will pull the image that I pushed that has your changes in it. 

But when you test, make sure you're testing without the Dockerfile you may have added in .ddev/web-build/Dockerfile, which would make your testing invalid.

**Comment by apotek** [comment]
> There is nothing you have to do with DDEV images. I pushed the changed image for you. All you need to use is the updated DDEV in this PR, [#5458 (comment)](https://github.com/ddev/ddev/pull/5458#issuecomment-1786177740) - It will pull the image that I pushed that has your changes in it.

Aha! So the binary is modified to use a different tag/image name that _you have already pushed up_! Now it all makes sense. Thank you! I was getting auth issues on push (for obvious reasons).

**Comment by rfay** [comment]
Thanks for chasing this down! And the upstream issues were a special treat.

**Pull request merged**
