### PR TITLE
build: revert to upstream Amplitude, fixes #5101

### LINKED ISSUE #5101: Replace go-amplitude fork with upstream now that blocking issue is resolved
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

See: https://github.com/amplitude/analytics-go/pull/56 for a resolution.

It looks like we need to simply pull in v1.0.1 to shed the tech debt of the fork.

### Describe your solution

Pull in the new version of the package, and remove the fork.

### Describe alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marklabrecque**
## The Issue

Reviewing the project, I noticed that we are using a fork for the explicit purpose of including a patch. This patch has now been incorporated into the upstream, so we can move back to using that upstream project and shed the fork.

Related:
* https://github.com/ddev/ddev/issues/5048
* #5101 

## How This PR Solves The Issue

I'm a new contributor and author of Go code, but I believe this replaces the fork with the upstream. Happy to make any adjustments or take on further work, if needed - let me know.

## Manual Testing Instructions

Nothing specific, to my knowledge. The usual things I guess?

## Related Issue Link(s)

https://github.com/amplitude/analytics-go/pull/56 is the PR that was needed to be incorporated into the upstream project.

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5103"></a>

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
Looks right to me. Needs careful manual testing with `export DDEV_VERBOSE=true` and doing more than 100 items.

**Review by gilbertsoft — APPROVED** [review]
Thanks, looks good!

**Comment by gilbertsoft** [comment]
Little side note @marklabrecque , it's always a good idea to run `go mod tidy` after changing modules which I did with the last commit.

**Comment by rfay** [comment]
Thanks so much for this @marklabrecque

**Comment by marklabrecque** [comment]
Thanks for the tip, @gilbertsoft ! I'll be sure to keep that in mind.

**Comment by gilbertsoft** [comment]
> Thanks for the tip, @gilbertsoft ! I'll be sure to keep that in mind.

We have added a check to the CI in the meantime which will remember us not to omit that step in the future :)

**Pull request merged**
