### PR TITLE
Change references to former repos to https://github.com/ddev/

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Issue

The various DDEV repositories were moved to https://github.com/ddev/.

## How This PR Solves The Issue

This patch changes all references to the new place.

### CODE REVIEW

**Comment by mattstein** [comment]
@gilbertsoft I’m not sure how best to review this, but if I check it out and search for `drud/ddev` I’ll see all kinds of remaining references in different places:

- `.go` imports
- `.md` documentation
- `.sh` scripts
- main project [README.md](https://github.com/ddev/ddev/blob/e5b29da5da76f87e82eaf0aef4fdfaefb0a108cc/README.md?plain=1#L5)

Can you help me understand the scope of this PR or how you’d like me to evaluate it?

**Comment by gilbertsoft** [comment]
> @gilbertsoft I’m not sure how best to review this, but if I check it out and search for `drud/ddev` I’ll see all kinds of remaining references in different places:
> 
>     * `.go` imports
> 
>     * `.md` documentation
> 
>     * `.sh` scripts
> 
>     * main project [README.md](https://github.com/ddev/ddev/blob/e5b29da5da76f87e82eaf0aef4fdfaefb0a108cc/README.md?plain=1#L5)
> 
> 
> Can you help me understand the scope of this PR or how you’d like me to evaluate it?

Not possible to check simply by searching for `drud/ddev` because it has changed only for Github so far. This PR should replace all references to the former GH repos in the drud GH organisation.

There are also many package references in the source which will be changed in a followup change, no need to change it at the moment.

I have searched for `drud` and checked every occurence if it has to be replaced or not. Hope this helps. And I have mainly requested your review for the docs btw but feel free to check also other places.

**Comment by rfay** [comment]
Yeah, all the go files have to be changed...

github.com/drud/ddev -> github.com/ddev/ddev

**Comment by mattstein** [comment]
Thanks! I understand there are a number of services and things that shouldn’t be changed yet, but there are many cases that seem like the could be. For example:

1. Why a reference to `https://circleci.com/gh/drud/ddev` [in the readme](https://github.com/ddev/ddev/blob/e5b29da5da76f87e82eaf0aef4fdfaefb0a108cc/README.md?plain=1#L5) is an occurrence that shouldn’t be replaced right now. (Redirects fine, appears to work as expected, and the current badge SVG URL fails while [an updated one](https://circleci.com/gh/ddev/ddev.svg?style=shield) works.)
2. Imports [like this](https://github.com/ddev/ddev/blob/c8929783ff45cfe970aad00ad556b54d11d0b203/cmd/ddev/main.go#L4) seem like they’re referencing the `drud` repo, but maybe I don’t understand the implication for Golang?

As far as the docs go, there are examples like [the Brew install line](https://github.com/ddev/ddev/blob/master/docs/content/users/install/ddev-installation.md?plain=1#L16) that I’m 90% sure are safe to update right now.

So I’m having trouble figuring out what you intentionally passed over and what needs to be called out.

**Comment by gilbertsoft** [comment]
> Thanks! I understand there are a number of services and things that shouldn’t be changed yet, but there are many cases that seem like they could be. For example:
> 
>     1. Why a reference to `https://circleci.com/gh/drud/ddev` [in the readme](https://github.com/ddev/ddev/blob/e5b29da5da76f87e82eaf0aef4fdfaefb0a108cc/README.md?plain=1#L5) is an occurrence that shouldn’t be replaced right now. (Redirects fine, appears to work as expected, and the current badge SVG URL fails while [an updated one](https://circleci.com/gh/ddev/ddev.svg?style=shield) works.)
> 
>     2. Imports [like this](https://github.com/ddev/ddev/blob/c8929783ff45cfe970aad00ad556b54d11d0b203/cmd/ddev/main.go#L4) seem like they’re referencing the `drud` repo, but maybe I don’t understand the implication for Golang?
> 
> 
> As far as the docs go, there are examples like [the Brew install line](https://github.com/ddev/ddev/blob/master/docs/content/users/install/ddev-installation.md?plain=1#L16) that I’m 90% sure are safe to update right now.
> 
> So I’m having trouble figuring out what you intentionally passed over and what needs to be called out.

Just added these changes too now. See also discussion at Discord.

**Comment by mattstein** [comment]
Of the few remaining references left, I’m guessing the following are Docker-related and that’s why they’re left alone for now:

- https://github.com/ddev/ddev/blob/master/containers/ddev-webserver/README.md?plain=1#L33
- https://github.com/ddev/ddev/blob/master/docs/content/developers/building-contributing.md?plain=1#L115
- https://github.com/ddev/ddev/blob/master/docs/content/developers/release-management.md?plain=1#L60-L61 (and a few more lines further down)
- https://github.com/ddev/ddev/blob/master/docs/content/users/configuration/config.md?plain=1#L548
- https://github.com/ddev/ddev/blob/master/docs/content/users/extend/customizing-images.md?plain=1#L87
- https://github.com/ddev/ddev/blob/master/docs/content/users/usage/commands.md?plain=1#L451

If I’m understanding correctly though, the following Homebrew and GitHub references can still be updated:

- https://github.com/ddev/ddev/blob/master/docs/content/developers/building-contributing.md?plain=1#L8
- https://github.com/ddev/ddev/blob/master/docs/content/developers/buildkite-testmachine-setup.md?plain=1#L125
- https://github.com/ddev/ddev/blob/master/docs/content/users/install/ddev-installation.md?plain=1#L16
- https://github.com/ddev/ddev/blob/master/docs/content/users/install/ddev-installation.md?plain=1#L282
- https://github.com/ddev/ddev/blob/master/docs/content/users/install/ddev-installation.md?plain=1#L312
- https://github.com/ddev/ddev/blob/master/docs/content/users/usage/faq.md?plain=1#L152
- https://github.com/ddev/ddev/blob/master/docs/content/users/install/shell-completion.md?plain=1#L47

**Review by mattstein — APPROVED** [review]

**Comment by rfay** [comment]
Followups:
- [ ] https://github.com/gilbertsoft/ddev/blob/3634e2b4935e9030e62f114434955faeccd384e0/.github/workflows/master-build.yml#L150

**Review by rfay — APPROVED** [review]
This is looking good. Followups can be done in a followup that doesn't have to run all the tests.

**Comment by rfay** [comment]
All tests successful. Manually checked buildkite tests, which aren't reporting back; circleci "normal_build_and_test" seems to be labelled differently now.

**Pull request merged**
