### PR TITLE
feat: remove segment.io support, fixes #5365

### LINKED ISSUE #5365: Remove support for Segment.io instrumentation
Amplitude seems to be working fine. We can pull the plug on Segment.io instrumentation.

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #5365 

We stopped actually using Segment.io in v1.22.0 because it's too expensive and we switched to using Amplitude

Now for v1.23, we can just remove that.

## Manual Testing Instructions

Manual testing is super-critical here. We need to make absolutely sure that we haven't broken Amplitude

- [ ] With amplitude enabled, take actions and see results in Amplitude

### CODE REVIEW

**Review by stasadev — CHANGES_REQUESTED** [review]
I tested this manually and I can see my user events in Amplitude with this PR.

To remove: `SegmentKey` in `Makefile` and in `.github/workflows/master-build.yml`.

I noticed comments for `InitAmplitude`, should it be done here as well?:

https://github.com/ddev/ddev/blob/55053f055955fe5e146e56954ed34ba22fc2c447/cmd/ddev/main.go#L14-L16

**Comment by rfay** [comment]
Thanks for the good eye. turned out that the check on `ddev config global` wasn't valid any more, we do it only on start (and now on ddev version)

On 
> This should be cleaned up

That was Simon's hope to remove init() usage in the future, which is definitely a valid hope.

**Review by stasadev — CHANGES_REQUESTED** [review]
Noticed one more leftover for `SegmentKey` in `.github/workflows/master-build.yml`

**Comment by rfay** [comment]
> Noticed one more leftover for SegmentKey

I guess I got distracted fixing that and adding the warning to `ddev version`

Turned out that hadn't been working for ages; we changed a long time ago to only check on `ddev start` but now added the check to `ddev version`.

**Review by stasadev — APPROVED** [review]

**Comment by rfay** [comment]
Rebased this and retested, and it seems to be right. I checked `go mod tidy` and `go mod vendor` and they seem to be unchanged.

**Pull request merged**
