### PR TITLE
feat: add aliases for custom commands, `art` alias for `artisan`, `ddev aliases` command, fixes #6443

### LINKED ISSUE #6443: Add support for custom command aliases
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

c.f. https://github.com/orgs/ddev/discussions/6431

Like the built-in `describe` command has aliases (`describe, status, st, desc`), I would like to be able to add aliases to my custom commands.

### Describe your solution

I propose the addition of an annotation (e.g., `Aliases`) for command files. I don't have a proposal for technical implementation. (I'm not experienced enough with DDEV internals yet to make one.)

### Describe alternatives

In the meantime, @rfay proposed symlinks as an alternative in https://github.com/orgs/ddev/discussions/6431#discussioncomment-10163083.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #6443

## How This PR Solves The Issue

Adds aliases for custom commands.
Adds `ddev art` alias for `ddev artisan`, this is the most used alias for Laravel.
Adds `ddev aliases` command:

```
$ ddev aliases
┌────────────────┬──────────────────┐
│ COMMAND        │ ALIASES          │
├────────────────┼──────────────────┤
│ artisan        │ art              │
├────────────────┼──────────────────┤
│ debug          │ d, dbg           │
├────────────────┼──────────────────┤
│ describe       │ status, st, desc │
├────────────────┼──────────────────┤
│ exec           │ .                │
├────────────────┼──────────────────┤
│ list           │ l, ls            │
├────────────────┼──────────────────┤
│ mutagen status │ mutagen st       │
├────────────────┼──────────────────┤
│ poweroff       │ powerdown        │
├────────────────┼──────────────────┤
│ start          │ add              │
├────────────────┼──────────────────┤
│ stop           │ rm, remove       │
└────────────────┴──────────────────┘
```

## Manual Testing Instructions

Try `ddev aliases` outside of the project, and inside the Laravel project.

Open some custom command, add:
```
## Aliases: cacheclear,cache-clear,cache:clear
```
Then run `ddev debug fix-command` and try the aliases.

Sadly there is no autocompletion for aliases.

Try `ddev art` in Laravel project.

### CODE REVIEW

**Comment by stasadev** [comment]
Open question: How should we filter what users can pass to aliases?

It now allows you to add things like these:

```
## Aliases: 🙂,test\ntest,::::::
```

```
ddev 🙂
ddev test\\ntest
ddev ::::::
```

**Comment by tyler36** [comment]
Thanks for this. I have a copy of the `artisan` command as `art` so this should cleanup that file.

## Test

1. Check current version

```shell
$ ddev -v
ddev version v1.23.3-33-g88ae3c3a4
```

2. Follow quickstart guide to install a Laravel project
3. Attempt to use alias

```shell
$ ddev art -v
Laravel Framework 11.5.0
...
```

## Test it handles conflicting aliases

1.  Copy `~/.ddev/commands/web/artisan` global command to `~/.ddev/commands/web/art`
4.  Update `Usage` to `## Usage: art [flags] [args]`, to create conflicting command
5.  Use DDEV

```shell
$ ddev -v
Command 'artisan' cannot have alias 'art' that is already in use by command 'art', skipping it
ddev version v1.23.3-33-g88ae3c3a4
```

6. Remove `~/.ddev/commands/web/art`
7. Use DDEV

```shell
$ ddev -v
ddev version v1.23.3-33-g88ae3c3a4
```

**Comment by tyler36** [comment]
> Open question: Should we filter what users can pass to aliases?

I don't think it's nessasary. I'm sure there's _someone_ out there that wants to `ddev ✉️` to open mailpit (not me).

**Comment by tyler36** [comment]
## Test Japanese characters (aka non-latin)

1. Create new alias

```bash
#!/bin/bash

## Description: Echo out something
## Usage: echo [flags] [args]
## Example: "ddev echo"
## Aliases: エコー,なる,鳴る
## ExecRaw: true

echo "$@"
```

2. DDEV restart
3.  Attempt to use command

```shell
# Main command
$ ddev echo 'hello'    
hello

# Command in katakana
$ ddev エコー 'hello'    
hello


# Command in katakana
$ ddev エコー 'hello'    
hello
# Command in kanji
$ ddev 鳴る 'hello'  
hello
```

**Comment by tyler36** [comment]
I can imagine getting support request like "why does `ddev gjkl` list artisan helper commands?"

To help with debugging this, I think we need to either

- print out aliases in `ddev help`. Eg.

```shell
$ ddev help
....

Available Commands:
  artisan          Run artisan CLI inside the web container (global shell web container command) (aliases: art)
```

- add a command to lists aliases. Eg.

```shell
$ ddev aliases
artisan          art
...
```

This will probably not be an issue with core commands (because of "ddev-generated"), but it could occur with custom commands, and addons that create custom commands.

**Comment by stasadev** [comment]
@tyler36, thank you for the review!

And these are great ideas with little helpers for aliases. I like both options, not sure which is better. I'll probably go with the simplest implementation I can make.

**Comment by tyler36** [comment]
> I like both options, not sure which is better. I'll probably go with the simplest implementation I can make.

Sounds good. We can always re-evalute in a year or so based on feedback. 

My initial though was `ddev help` but thats getting pretty dense, especially if commands have multiple aliases. 🤷

**Comment by stasadev** [comment]
Modifying `ddev help` would mean overriding the standard command, as we do for `ddev help -j`, which is quite complicated.
So I added the `ddev aliases` command.

**Review by rfay — APPROVED** [review]
Wow, am I impressed that you actually caught all the go-based aliases. I didn't know that `ddev l` was a thing. 

I tried adding aliases to `ddev launch` and it was fine, and accidental overrides were detected. 

So great, and it seems to me like there's not much risk either. 

Don't forget to add to release notes if you pull this.

**Pull request merged**
