### PR TITLE
fix: default file/uploads location for Silverstripe

### PR DESCRIPTION
**Pull request by Firesphere**
## The Issue

`ddev import-files` on Silverstripe does not have a default import location set.

## How This PR Solves The Issue

Adds a default UploadDirs method to Silverstripe, so the default (`public/assets`) is properly detected.

## Manual Testing Instructions

Run an import of assets.

## Automated Testing Overview

Added a test which checks for each known `getUploadDirs` method, if the return matches a set of default expected values.

## Related Issue Link(s)

Depends on 
* #5234

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5241"></a>

### CODE REVIEW

**Comment by Firesphere** [comment]
Seems so far the Colima tests just crashed. No big deal though, it's a 3-liner.
I'll make it fully working, and hopefully also, while at it, a few tiny fixes?

@rfay I noticed that the `ddev list` command works but since "Silverstripe" is longer than the currently allocated 9 characters, it gets a break.
Do you want a separate PR for that (Changing the limit from 9 to 13), or are you okay with putting it all in one PR?

I don't mind either way, but multiple PRs for just Silverstripe minor fixes feels a tad overkill?

**Comment by rfay** [comment]
Rebased and the requisite PR is now pulled, so please check it over and take a look at the silverstripe files tarball. Thanks!

**Comment by Firesphere** [comment]
I'll try to make some time free for it! But no promises... Life is surely getting in the way at the moment :)

**Comment by Firesphere** [comment]
I've added a very basic test that checks if the upload dir is at least not empty.

I'm a tad short on time right now, but I'm trying to get the tests to match an actual expectation instead of only "not empty"

**Comment by rfay** [comment]
Please edit the OP to add a complete description of how to test import-files, thanks!

Note that colima on amd64 has been broken for the last couple of weeks, so don't worry about that. 

> Mildly unsure why the no-bind-mounts=false test keeps failing... It succeeds locally

Not sure which test you're referring to, a link would be good. 

image

**Comment by Firesphere** [comment]
It's this one, the Colima test indeed :) :
https://github.com/ddev/ddev/actions/runs/6019812935/job/16330172143?pr=5241

**Comment by rfay** [comment]
Rebased. I hope things have calmed down now @Firesphere and that the new life is great! Let me know if you want to go forward with this one.

**Comment by rfay** [comment]
I'll close this about Oct 1 if it doesn't get attention, thanks @Firesphere . After that it can be reopened when you are ready to return to it.

**Comment by Firesphere** [comment]
Apologies, both work and personal life are very stressful and busy at the moment.

I'll get back to tidying this up probably not before mid October

**Comment by Firesphere** [comment]
Update, got some spare time.

I _think_ this is what I completely intended to achieve.

Set the upload dir, and test for the known project types that have an upload dir, that it is what is expected from default settings.

**Comment by rfay** [comment]
Thanks. I know what it's like to have too much else to do. Wasn't trying to pressure you, just try to keep things moving so it doesn't get too messy around here.

**Comment by rfay** [comment]
Sorry, this got lost in the older PRs and now I'm less available next few weeks. Will try to get it reviewed.

**Review by stasadev — CHANGES_REQUESTED** [review]
@Firesphere 

Tested it with:

```
mkdir my-silverstripe-app
cd my-silverstripe-app
ddev config --project-type=silverstripe --docroot=public --create-docroot
ddev composer create --prefer-dist --no-scripts silverstripe/installer -y

mkdir my-assets && touch my-assets/asset.txt
ddev import-files --source=my-assets
Error: failed to import files for my-silverstripe-app: unable to import to /home/stas/code/ddev/my-silverstripe-app/public/public/assets: parent directory does not exist
```

But it tries to use `public/public/assets`. I believe it is because `--docroot=public`

I used quickstart https://ddev.readthedocs.io/en/latest/users/quickstart/#silverstripe

**Comment by Firesphere** [comment]
Hm, okay, I did not expect that :D . I'll have a look. Cheers!

**Comment by Firesphere** [comment]
It was a tad dumb of me, the upload dir is relative to the public dir, it was indeed creating `public/public/assets` constantly.

A "simple" matter of not including `public` in the upload dir should solve it.

**Comment by rfay** [comment]
Thanks for the followup!

**Review by rfay — APPROVED** [review]
Looks good to me. Let me know when you're happy with it and I'll pull.

**Comment by Firesphere** [comment]
As far as I'm concerned/aware, it's good to go. It has all the tests and solves the original problem mentioned in #5234

**Comment by rfay** [comment]
@stasadev can take a look tomorrow and in it goes!

**Review by stasadev — APPROVED** [review]
Looks good to me.

**Pull request merged**
